--------------------------------------------------------
--  파일이 생성됨 - 화요일-6월-02-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CHAT_MEMBERS
--------------------------------------------------------

  CREATE TABLE "MOYEODDUGI"."CHAT_MEMBERS" 
   (	"MEMBER_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ROOM_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"IS_HOST" CHAR(1 BYTE) DEFAULT 'N', 
	"JOINED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CHAT_MESSAGES
--------------------------------------------------------

  CREATE TABLE "MOYEODDUGI"."CHAT_MESSAGES" 
   (	"MESSAGE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ROOM_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"CONTENT" VARCHAR2(2000 BYTE), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CHAT_ROOMS
--------------------------------------------------------

  CREATE TABLE "MOYEODDUGI"."CHAT_ROOMS" 
   (	"ROOM_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"POST_ID" NUMBER, 
	"ROOM_NAME" VARCHAR2(200 BYTE), 
	"MAX_MEMBERS" NUMBER, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMMENTS
--------------------------------------------------------

  CREATE TABLE "MOYEODDUGI"."COMMENTS" 
   (	"COMMENT_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TARGET_TYPE" VARCHAR2(10 BYTE), 
	"TARGET_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"CONTENT" VARCHAR2(1000 BYTE), 
	"PARENT_ID" NUMBER, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"REPLY_TO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FOLLOWS
--------------------------------------------------------

  CREATE TABLE "MOYEODDUGI"."FOLLOWS" 
   (	"FOLLOW_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"FOLLOWER_ID" NUMBER, 
	"FOLLOWING_ID" NUMBER, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LIKES
--------------------------------------------------------

  CREATE TABLE "MOYEODDUGI"."LIKES" 
   (	"LIKE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USER_ID" NUMBER, 
	"TARGET_TYPE" VARCHAR2(10 BYTE), 
	"TARGET_ID" NUMBER, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NOTIFICATIONS
--------------------------------------------------------

  CREATE TABLE "MOYEODDUGI"."NOTIFICATIONS" 
   (	"NOTI_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"RECEIVER_ID" NUMBER, 
	"SENDER_ID" NUMBER, 
	"NOTI_TYPE" VARCHAR2(20 BYTE), 
	"TARGET_TYPE" VARCHAR2(10 BYTE), 
	"TARGET_ID" NUMBER, 
	"MESSAGE" VARCHAR2(500 BYTE), 
	"IS_READ" CHAR(1 BYTE) DEFAULT 'N', 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PATTERNS
--------------------------------------------------------

  CREATE TABLE "MOYEODDUGI"."PATTERNS" 
   (	"PATTERN_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USER_ID" NUMBER, 
	"TITLE" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"NEEDLE_TYPE" VARCHAR2(10 BYTE), 
	"DIFFICULTY" VARCHAR2(10 BYTE), 
	"YARN_TYPE" VARCHAR2(100 BYTE), 
	"NEEDLE_SIZE" VARCHAR2(50 BYTE), 
	"FINISHED_SIZE" VARCHAR2(100 BYTE), 
	"WORK_TIME" VARCHAR2(50 BYTE), 
	"THUMBNAIL_IMG" VARCHAR2(500 BYTE), 
	"VIEW_COUNT" NUMBER DEFAULT 0, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"CATEGORY" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PATTERN_IMAGES
--------------------------------------------------------

  CREATE TABLE "MOYEODDUGI"."PATTERN_IMAGES" 
   (	"IMAGE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PATTERN_ID" NUMBER, 
	"IMAGE_URL" VARCHAR2(500 BYTE), 
	"SORT_ORDER" NUMBER DEFAULT 0, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PATTERN_TAGS
--------------------------------------------------------

  CREATE TABLE "MOYEODDUGI"."PATTERN_TAGS" 
   (	"TAG_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PATTERN_ID" NUMBER, 
	"TAG_NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PLACES
--------------------------------------------------------

  CREATE TABLE "MOYEODDUGI"."PLACES" 
   (	"PLACE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USER_ID" NUMBER, 
	"PLACE_NAME" VARCHAR2(100 BYTE), 
	"PLACE_TYPE" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(300 BYTE), 
	"LATITUDE" NUMBER(10,7), 
	"LONGITUDE" NUMBER(10,7), 
	"ALLOW_STATUS" VARCHAR2(10 BYTE), 
	"HAS_WIDE_TABLE" CHAR(1 BYTE) DEFAULT 'N', 
	"HAS_OUTLET" CHAR(1 BYTE) DEFAULT 'N', 
	"IS_QUIET" CHAR(1 BYTE) DEFAULT 'N', 
	"NO_TIME_LIMIT" CHAR(1 BYTE) DEFAULT 'N', 
	"HAS_MANY_SEATS" CHAR(1 BYTE) DEFAULT 'N', 
	"NO_MIN_ORDER" CHAR(1 BYTE) DEFAULT 'N', 
	"HAS_PARKING" CHAR(1 BYTE) DEFAULT 'N', 
	"IS_24HOURS" CHAR(1 BYTE) DEFAULT 'N', 
	"HAS_OUTDOOR" CHAR(1 BYTE) DEFAULT 'N', 
	"PET_FRIENDLY" CHAR(1 BYTE) DEFAULT 'N', 
	"HAS_FOOD" CHAR(1 BYTE) DEFAULT 'N', 
	"HAS_RESTROOM" CHAR(1 BYTE) DEFAULT 'N', 
	"PLACE_IMG" VARCHAR2(500 BYTE), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PLACE_REVIEWS
--------------------------------------------------------

  CREATE TABLE "MOYEODDUGI"."PLACE_REVIEWS" 
   (	"REVIEW_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PLACE_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"CONTENT" VARCHAR2(500 BYTE), 
	"ALLOW_STATUS" VARCHAR2(20 BYTE), 
	"REVIEW_IMG" VARCHAR2(500 BYTE), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table POSTS
--------------------------------------------------------

  CREATE TABLE "MOYEODDUGI"."POSTS" 
   (	"POST_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USER_ID" NUMBER, 
	"BOARD_TYPE" VARCHAR2(20 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" VARCHAR2(4000 BYTE), 
	"VIEW_COUNT" NUMBER DEFAULT 0, 
	"GATHER_STATUS" VARCHAR2(10 BYTE), 
	"GATHER_COUNT" NUMBER, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table POST_IMAGES
--------------------------------------------------------

  CREATE TABLE "MOYEODDUGI"."POST_IMAGES" 
   (	"IMAGE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"POST_ID" NUMBER, 
	"IMAGE_URL" VARCHAR2(500 BYTE), 
	"IS_THUMBNAIL" CHAR(1 BYTE) DEFAULT 'N', 
	"SORT_ORDER" NUMBER DEFAULT 0, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SCRAPS
--------------------------------------------------------

  CREATE TABLE "MOYEODDUGI"."SCRAPS" 
   (	"SCRAP_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USER_ID" NUMBER, 
	"TARGET_TYPE" VARCHAR2(10 BYTE), 
	"TARGET_ID" NUMBER, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "MOYEODDUGI"."USERS" 
   (	"USER_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE), 
	"SOCIAL_PROVIDER" VARCHAR2(20 BYTE), 
	"SOCIAL_ID" VARCHAR2(100 BYTE), 
	"NICKNAME" VARCHAR2(50 BYTE), 
	"PROFILE_IMG" VARCHAR2(500 BYTE), 
	"BIO" VARCHAR2(200 BYTE), 
	"USER_ROLE" VARCHAR2(10 BYTE) DEFAULT 'USER', 
	"STATUS" VARCHAR2(10 BYTE) DEFAULT 'ACTIVE', 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"USER_NAME" VARCHAR2(50 BYTE), 
	"BIRTH_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into MOYEODDUGI.CHAT_MEMBERS
SET DEFINE OFF;
REM INSERTING into MOYEODDUGI.CHAT_MESSAGES
SET DEFINE OFF;
REM INSERTING into MOYEODDUGI.CHAT_ROOMS
SET DEFINE OFF;
REM INSERTING into MOYEODDUGI.COMMENTS
SET DEFINE OFF;
Insert into MOYEODDUGI.COMMENTS (COMMENT_ID,TARGET_TYPE,TARGET_ID,USER_ID,CONTENT,PARENT_ID,CREATED_AT,UPDATED_AT,REPLY_TO) values (35,'POST',25,41,'@다떠베이저 진짜 강추합니다.',32,to_timestamp('26/06/02 15:11:59.173000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/02 15:11:59.173000000','RR/MM/DD HH24:MI:SSXFF'),34);
Insert into MOYEODDUGI.COMMENTS (COMMENT_ID,TARGET_TYPE,TARGET_ID,USER_ID,CONTENT,PARENT_ID,CREATED_AT,UPDATED_AT,REPLY_TO) values (36,'POST',13,41,'@하루의하루 저도 있습니다.',1,to_timestamp('26/06/02 15:12:22.517000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/02 15:12:22.517000000','RR/MM/DD HH24:MI:SSXFF'),3);
Insert into MOYEODDUGI.COMMENTS (COMMENT_ID,TARGET_TYPE,TARGET_ID,USER_ID,CONTENT,PARENT_ID,CREATED_AT,UPDATED_AT,REPLY_TO) values (24,'PATTERN',11,21,'우와~',null,to_timestamp('26/06/02 10:08:18.410000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/02 10:08:18.410000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into MOYEODDUGI.COMMENTS (COMMENT_ID,TARGET_TYPE,TARGET_ID,USER_ID,CONTENT,PARENT_ID,CREATED_AT,UPDATED_AT,REPLY_TO) values (32,'POST',25,41,'아주 좋은 카페였습니다.',null,to_timestamp('26/06/02 15:07:39.047000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/02 15:07:39.047000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into MOYEODDUGI.COMMENTS (COMMENT_ID,TARGET_TYPE,TARGET_ID,USER_ID,CONTENT,PARENT_ID,CREATED_AT,UPDATED_AT,REPLY_TO) values (1,'POST',13,1,'가입인사합니다 ㅋㅋ',null,to_timestamp('26/06/01 10:32:03.053000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 12:04:42.088000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into MOYEODDUGI.COMMENTS (COMMENT_ID,TARGET_TYPE,TARGET_ID,USER_ID,CONTENT,PARENT_ID,CREATED_AT,UPDATED_AT,REPLY_TO) values (20,'POST',13,1,'ㅋㅋㅋㅋㅋ',1,to_timestamp('26/06/01 12:21:38.512000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 12:21:38.512000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into MOYEODDUGI.COMMENTS (COMMENT_ID,TARGET_TYPE,TARGET_ID,USER_ID,CONTENT,PARENT_ID,CREATED_AT,UPDATED_AT,REPLY_TO) values (3,'POST',13,21,'저 있어요 ㅎㅎ',1,to_timestamp('26/06/01 10:32:55.605000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 10:32:55.605000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into MOYEODDUGI.COMMENTS (COMMENT_ID,TARGET_TYPE,TARGET_ID,USER_ID,CONTENT,PARENT_ID,CREATED_AT,UPDATED_AT,REPLY_TO) values (4,'POST',13,21,'댓글 입니다.',null,to_timestamp('26/06/01 10:38:19.063000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 10:38:19.063000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into MOYEODDUGI.COMMENTS (COMMENT_ID,TARGET_TYPE,TARGET_ID,USER_ID,CONTENT,PARENT_ID,CREATED_AT,UPDATED_AT,REPLY_TO) values (5,'POST',13,21,'어디에 달리는거죠',1,to_timestamp('26/06/01 10:42:52.839000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 10:42:52.839000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into MOYEODDUGI.COMMENTS (COMMENT_ID,TARGET_TYPE,TARGET_ID,USER_ID,CONTENT,PARENT_ID,CREATED_AT,UPDATED_AT,REPLY_TO) values (21,'POST',13,1,'@뜨개중독 ㅋㅋㅋㅋ',1,to_timestamp('26/06/01 12:21:42.351000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 12:21:42.351000000','RR/MM/DD HH24:MI:SSXFF'),20);
Insert into MOYEODDUGI.COMMENTS (COMMENT_ID,TARGET_TYPE,TARGET_ID,USER_ID,CONTENT,PARENT_ID,CREATED_AT,UPDATED_AT,REPLY_TO) values (7,'POST',13,1,'하루의하루에게 답글',1,to_timestamp('26/06/01 11:19:17.657000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 11:19:17.657000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into MOYEODDUGI.COMMENTS (COMMENT_ID,TARGET_TYPE,TARGET_ID,USER_ID,CONTENT,PARENT_ID,CREATED_AT,UPDATED_AT,REPLY_TO) values (22,'POST',13,1,'@뜨개중독 ㅎㅎㅎ',1,to_timestamp('26/06/01 12:21:50.416000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 12:21:50.416000000','RR/MM/DD HH24:MI:SSXFF'),21);
Insert into MOYEODDUGI.COMMENTS (COMMENT_ID,TARGET_TYPE,TARGET_ID,USER_ID,CONTENT,PARENT_ID,CREATED_AT,UPDATED_AT,REPLY_TO) values (23,'POST',13,1,'@뜨개중독 ㅎㅎㅎㅎㅎㅎ',1,to_timestamp('26/06/01 12:22:00.184000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 12:22:00.184000000','RR/MM/DD HH24:MI:SSXFF'),21);
Insert into MOYEODDUGI.COMMENTS (COMMENT_ID,TARGET_TYPE,TARGET_ID,USER_ID,CONTENT,PARENT_ID,CREATED_AT,UPDATED_AT,REPLY_TO) values (10,'POST',12,1,'유튜브 추천합니다.',null,to_timestamp('26/06/01 11:45:41.919000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 11:45:41.919000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into MOYEODDUGI.COMMENTS (COMMENT_ID,TARGET_TYPE,TARGET_ID,USER_ID,CONTENT,PARENT_ID,CREATED_AT,UPDATED_AT,REPLY_TO) values (11,'POST',12,1,'링크는 마이페이지에 있어요 ㅎ',10,to_timestamp('26/06/01 11:45:50.955000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 11:45:50.955000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into MOYEODDUGI.COMMENTS (COMMENT_ID,TARGET_TYPE,TARGET_ID,USER_ID,CONTENT,PARENT_ID,CREATED_AT,UPDATED_AT,REPLY_TO) values (26,'PATTERN',13,21,'좋아요 부탁드립니다 ^^',null,to_timestamp('26/06/02 10:52:19.360000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/02 10:52:19.360000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into MOYEODDUGI.COMMENTS (COMMENT_ID,TARGET_TYPE,TARGET_ID,USER_ID,CONTENT,PARENT_ID,CREATED_AT,UPDATED_AT,REPLY_TO) values (27,'PATTERN',13,21,'감사합니다.',26,to_timestamp('26/06/02 10:52:24.872000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/02 10:52:24.872000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into MOYEODDUGI.COMMENTS (COMMENT_ID,TARGET_TYPE,TARGET_ID,USER_ID,CONTENT,PARENT_ID,CREATED_AT,UPDATED_AT,REPLY_TO) values (30,'PATTERN',13,21,'고맙습니다.',26,to_timestamp('26/06/02 10:58:06.433000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/02 10:58:06.433000000','RR/MM/DD HH24:MI:SSXFF'),27);
Insert into MOYEODDUGI.COMMENTS (COMMENT_ID,TARGET_TYPE,TARGET_ID,USER_ID,CONTENT,PARENT_ID,CREATED_AT,UPDATED_AT,REPLY_TO) values (31,'PATTERN',13,41,'정말 멋진 작품입니다. 제 새 헬멧으로 손색이 없네요.',null,to_timestamp('26/06/02 14:34:34.131000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/02 14:34:34.131000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into MOYEODDUGI.COMMENTS (COMMENT_ID,TARGET_TYPE,TARGET_ID,USER_ID,CONTENT,PARENT_ID,CREATED_AT,UPDATED_AT,REPLY_TO) values (38,'POST',30,21,'와~~ 너무 멋집니다!! 최고 최고! ㅎㅎ',null,to_timestamp('26/06/02 17:05:15.174000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/02 17:05:15.174000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into MOYEODDUGI.COMMENTS (COMMENT_ID,TARGET_TYPE,TARGET_ID,USER_ID,CONTENT,PARENT_ID,CREATED_AT,UPDATED_AT,REPLY_TO) values (34,'POST',25,41,'또 가고 싶습니다.',32,to_timestamp('26/06/02 15:10:58.964000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/02 15:10:58.964000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into MOYEODDUGI.COMMENTS (COMMENT_ID,TARGET_TYPE,TARGET_ID,USER_ID,CONTENT,PARENT_ID,CREATED_AT,UPDATED_AT,REPLY_TO) values (37,'POST',28,41,'기대해 주시라주시라',null,to_timestamp('26/06/02 15:54:11.930000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/02 15:54:11.930000000','RR/MM/DD HH24:MI:SSXFF'),null);
REM INSERTING into MOYEODDUGI.FOLLOWS
SET DEFINE OFF;
Insert into MOYEODDUGI.FOLLOWS (FOLLOW_ID,FOLLOWER_ID,FOLLOWING_ID,CREATED_AT) values (3,41,21,to_timestamp('26/06/02 16:55:26.157000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.FOLLOWS (FOLLOW_ID,FOLLOWER_ID,FOLLOWING_ID,CREATED_AT) values (4,21,41,to_timestamp('26/06/02 18:05:17.344000000','RR/MM/DD HH24:MI:SSXFF'));
REM INSERTING into MOYEODDUGI.LIKES
SET DEFINE OFF;
Insert into MOYEODDUGI.LIKES (LIKE_ID,USER_ID,TARGET_TYPE,TARGET_ID,CREATED_AT) values (17,21,'POST',30,to_timestamp('26/06/02 18:05:04.438000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.LIKES (LIKE_ID,USER_ID,TARGET_TYPE,TARGET_ID,CREATED_AT) values (12,21,'POST',13,to_timestamp('26/06/02 12:56:23.336000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.LIKES (LIKE_ID,USER_ID,TARGET_TYPE,TARGET_ID,CREATED_AT) values (4,1,'POST',13,to_timestamp('26/06/01 12:43:44.008000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.LIKES (LIKE_ID,USER_ID,TARGET_TYPE,TARGET_ID,CREATED_AT) values (5,1,'POST',12,to_timestamp('26/06/01 12:43:44.991000000','RR/MM/DD HH24:MI:SSXFF'));
REM INSERTING into MOYEODDUGI.NOTIFICATIONS
SET DEFINE OFF;
REM INSERTING into MOYEODDUGI.PATTERNS
SET DEFINE OFF;
Insert into MOYEODDUGI.PATTERNS (PATTERN_ID,USER_ID,TITLE,DESCRIPTION,NEEDLE_TYPE,DIFFICULTY,YARN_TYPE,NEEDLE_SIZE,FINISHED_SIZE,WORK_TIME,THUMBNAIL_IMG,VIEW_COUNT,CREATED_AT,UPDATED_AT,CATEGORY) values (14,41,'강아지 픽셀 뜨기','코바늘, 대바늘 상관 없는 픽셀 뜨기 도안입니다.
나중에 이어 붙여서 가방이나 파우치 만들면 귀여워요.','코바늘','입문','아무실이나 가능','코바늘 5호','가로,세로 10cm','30분','/uploads/patterns/pattern_1780380426645.jpg',0,to_timestamp('26/06/02 15:07:06.648000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/02 15:07:06.648000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into MOYEODDUGI.PATTERNS (PATTERN_ID,USER_ID,TITLE,DESCRIPTION,NEEDLE_TYPE,DIFFICULTY,YARN_TYPE,NEEDLE_SIZE,FINISHED_SIZE,WORK_TIME,THUMBNAIL_IMG,VIEW_COUNT,CREATED_AT,UPDATED_AT,CATEGORY) values (13,21,'체커 모자','흑백 체커보드 패턴의 코바늘 버킷햇이에요. 짧은뜨기로 빼곡하게 채워 형태감이 탄탄하고, 배색 뜨기로 체크 패턴을 표현해요. 중급 난이도지만 패턴이 규칙적이라 익숙해지면 리듬감 있게 뜰 수 있어요. 여름철 데일리 아이템으로 딱이에요!','코바늘','초급','면사 (코튼사) 흑/백 2색','6mm ','머리 둘레 56~58cm','2-3시간','/uploads/patterns/pattern_1780364158763.jpg',0,to_timestamp('26/06/02 10:35:58.774000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/02 10:35:58.774000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into MOYEODDUGI.PATTERNS (PATTERN_ID,USER_ID,TITLE,DESCRIPTION,NEEDLE_TYPE,DIFFICULTY,YARN_TYPE,NEEDLE_SIZE,FINISHED_SIZE,WORK_TIME,THUMBNAIL_IMG,VIEW_COUNT,CREATED_AT,UPDATED_AT,CATEGORY) values (12,21,'코바늘 네트백 (마르쉐백)','코바늘로 뜨는 감성 네트백입니다. 
망사 패턴으로 가볍고 통기성이 좋아 장보기백, 비치백으로 활용하기 좋아요. 
긴뜨기와 사슬뜨기의 반복으로 초급자도 도전할 수 있어요.','코바늘','초급','면사 (코튼사)','4mm (7호)','가로 35cm x 세로 40cm (손잡이 포함)','3-4시간','/uploads/patterns/pattern_1780364103344.jpg',0,to_timestamp('26/06/02 10:35:03.375000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/02 10:35:03.375000000','RR/MM/DD HH24:MI:SSXFF'),null);
REM INSERTING into MOYEODDUGI.PATTERN_IMAGES
SET DEFINE OFF;
Insert into MOYEODDUGI.PATTERN_IMAGES (IMAGE_ID,PATTERN_ID,IMAGE_URL,SORT_ORDER,CREATED_AT) values (6,14,'/uploads/patterns/pattern_1780380426645.jpg',0,to_timestamp('26/06/02 15:07:06.649000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PATTERN_IMAGES (IMAGE_ID,PATTERN_ID,IMAGE_URL,SORT_ORDER,CREATED_AT) values (1,12,'/uploads/patterns/pattern_1780364103344.jpg',0,to_timestamp('26/06/02 10:35:03.405000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PATTERN_IMAGES (IMAGE_ID,PATTERN_ID,IMAGE_URL,SORT_ORDER,CREATED_AT) values (2,12,'/uploads/patterns/pattern_1780364103353.jpg',1,to_timestamp('26/06/02 10:35:03.407000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PATTERN_IMAGES (IMAGE_ID,PATTERN_ID,IMAGE_URL,SORT_ORDER,CREATED_AT) values (3,12,'/uploads/patterns/pattern_1780364103366.jpg',2,to_timestamp('26/06/02 10:35:03.408000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PATTERN_IMAGES (IMAGE_ID,PATTERN_ID,IMAGE_URL,SORT_ORDER,CREATED_AT) values (4,13,'/uploads/patterns/pattern_1780364158763.jpg',0,to_timestamp('26/06/02 10:35:58.774000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PATTERN_IMAGES (IMAGE_ID,PATTERN_ID,IMAGE_URL,SORT_ORDER,CREATED_AT) values (5,13,'/uploads/patterns/pattern_1780364158768.jpg',1,to_timestamp('26/06/02 10:35:58.775000000','RR/MM/DD HH24:MI:SSXFF'));
REM INSERTING into MOYEODDUGI.PATTERN_TAGS
SET DEFINE OFF;
Insert into MOYEODDUGI.PATTERN_TAGS (TAG_ID,PATTERN_ID,TAG_NAME) values (27,14,'소품');
Insert into MOYEODDUGI.PATTERN_TAGS (TAG_ID,PATTERN_ID,TAG_NAME) values (22,12,'소품');
Insert into MOYEODDUGI.PATTERN_TAGS (TAG_ID,PATTERN_ID,TAG_NAME) values (23,12,'가방');
Insert into MOYEODDUGI.PATTERN_TAGS (TAG_ID,PATTERN_ID,TAG_NAME) values (25,13,'모자');
Insert into MOYEODDUGI.PATTERN_TAGS (TAG_ID,PATTERN_ID,TAG_NAME) values (26,13,'의류');
Insert into MOYEODDUGI.PATTERN_TAGS (TAG_ID,PATTERN_ID,TAG_NAME) values (24,13,'소품');
REM INSERTING into MOYEODDUGI.PLACES
SET DEFINE OFF;
Insert into MOYEODDUGI.PLACES (PLACE_ID,USER_ID,PLACE_NAME,PLACE_TYPE,ADDRESS,LATITUDE,LONGITUDE,ALLOW_STATUS,HAS_WIDE_TABLE,HAS_OUTLET,IS_QUIET,NO_TIME_LIMIT,HAS_MANY_SEATS,NO_MIN_ORDER,HAS_PARKING,IS_24HOURS,HAS_OUTDOOR,PET_FRIENDLY,HAS_FOOD,HAS_RESTROOM,PLACE_IMG,CREATED_AT,UPDATED_AT) values (1,1,'스타벅스 부평점','카페','인천광역시 부평구 부평대로 1',37.4899,126.7235,'허용','Y','Y','N','N','N','N','N','N','N','N','N','N',null,to_timestamp('26/06/01 15:06:00.102000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 15:06:00.102000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACES (PLACE_ID,USER_ID,PLACE_NAME,PLACE_TYPE,ADDRESS,LATITUDE,LONGITUDE,ALLOW_STATUS,HAS_WIDE_TABLE,HAS_OUTLET,IS_QUIET,NO_TIME_LIMIT,HAS_MANY_SEATS,NO_MIN_ORDER,HAS_PARKING,IS_24HOURS,HAS_OUTDOOR,PET_FRIENDLY,HAS_FOOD,HAS_RESTROOM,PLACE_IMG,CREATED_AT,UPDATED_AT) values (2,1,'이디야 부평역점','카페','인천광역시 부평구 부평로 10',37.4877,126.7219,'금지','N','N','N','N','N','N','N','N','N','N','N','N',null,to_timestamp('26/06/01 15:06:00.109000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 15:06:00.109000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACES (PLACE_ID,USER_ID,PLACE_NAME,PLACE_TYPE,ADDRESS,LATITUDE,LONGITUDE,ALLOW_STATUS,HAS_WIDE_TABLE,HAS_OUTLET,IS_QUIET,NO_TIME_LIMIT,HAS_MANY_SEATS,NO_MIN_ORDER,HAS_PARKING,IS_24HOURS,HAS_OUTDOOR,PET_FRIENDLY,HAS_FOOD,HAS_RESTROOM,PLACE_IMG,CREATED_AT,UPDATED_AT) values (3,1,'스타벅스 홍대입구점','카페','서울특별시 마포구 양화로 160',37.5563,126.9226,'허용','Y','Y','N','N','Y','N','N','N','N','N','N','Y',null,to_timestamp('26/06/01 15:24:38.458000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 15:24:38.458000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACES (PLACE_ID,USER_ID,PLACE_NAME,PLACE_TYPE,ADDRESS,LATITUDE,LONGITUDE,ALLOW_STATUS,HAS_WIDE_TABLE,HAS_OUTLET,IS_QUIET,NO_TIME_LIMIT,HAS_MANY_SEATS,NO_MIN_ORDER,HAS_PARKING,IS_24HOURS,HAS_OUTDOOR,PET_FRIENDLY,HAS_FOOD,HAS_RESTROOM,PLACE_IMG,CREATED_AT,UPDATED_AT) values (4,1,'이디야 강남점','카페','서울특별시 강남구 강남대로 396',37.4979,127.0276,'금지','N','N','N','N','N','N','N','N','N','N','N','Y',null,to_timestamp('26/06/01 15:24:38.465000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 15:24:38.465000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACES (PLACE_ID,USER_ID,PLACE_NAME,PLACE_TYPE,ADDRESS,LATITUDE,LONGITUDE,ALLOW_STATUS,HAS_WIDE_TABLE,HAS_OUTLET,IS_QUIET,NO_TIME_LIMIT,HAS_MANY_SEATS,NO_MIN_ORDER,HAS_PARKING,IS_24HOURS,HAS_OUTDOOR,PET_FRIENDLY,HAS_FOOD,HAS_RESTROOM,PLACE_IMG,CREATED_AT,UPDATED_AT) values (6,1,'할리스 건대점','카페','서울특별시 광진구 능동로 126',37.5403,127.07,'허용','N','Y','Y','Y','N','N','N','N','N','N','N','Y',null,to_timestamp('26/06/01 15:24:38.551000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 15:24:38.551000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACES (PLACE_ID,USER_ID,PLACE_NAME,PLACE_TYPE,ADDRESS,LATITUDE,LONGITUDE,ALLOW_STATUS,HAS_WIDE_TABLE,HAS_OUTLET,IS_QUIET,NO_TIME_LIMIT,HAS_MANY_SEATS,NO_MIN_ORDER,HAS_PARKING,IS_24HOURS,HAS_OUTDOOR,PET_FRIENDLY,HAS_FOOD,HAS_RESTROOM,PLACE_IMG,CREATED_AT,UPDATED_AT) values (7,1,'메가커피 종로점','카페','서울특별시 종로구 종로 51',37.5706,126.9897,'금지','N','N','N','N','Y','N','N','N','N','N','N','Y',null,to_timestamp('26/06/01 15:24:38.555000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 15:24:38.555000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACES (PLACE_ID,USER_ID,PLACE_NAME,PLACE_TYPE,ADDRESS,LATITUDE,LONGITUDE,ALLOW_STATUS,HAS_WIDE_TABLE,HAS_OUTLET,IS_QUIET,NO_TIME_LIMIT,HAS_MANY_SEATS,NO_MIN_ORDER,HAS_PARKING,IS_24HOURS,HAS_OUTDOOR,PET_FRIENDLY,HAS_FOOD,HAS_RESTROOM,PLACE_IMG,CREATED_AT,UPDATED_AT) values (8,1,'카페베네 합정점','카페','서울특별시 마포구 합정동 358',37.5495,126.9143,'허용','Y','Y','Y','Y','Y','N','N','N','N','N','N','Y',null,to_timestamp('26/06/01 15:24:38.560000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 15:24:38.560000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACES (PLACE_ID,USER_ID,PLACE_NAME,PLACE_TYPE,ADDRESS,LATITUDE,LONGITUDE,ALLOW_STATUS,HAS_WIDE_TABLE,HAS_OUTLET,IS_QUIET,NO_TIME_LIMIT,HAS_MANY_SEATS,NO_MIN_ORDER,HAS_PARKING,IS_24HOURS,HAS_OUTDOOR,PET_FRIENDLY,HAS_FOOD,HAS_RESTROOM,PLACE_IMG,CREATED_AT,UPDATED_AT) values (10,1,'폴바셋 서울숲점','카페','서울특별시 성동구 왕십리로 83',37.5445,127.0441,'허용','Y','Y','Y','N','N','N','N','N','N','Y','N','Y',null,to_timestamp('26/06/01 15:24:38.585000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 15:24:38.585000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACES (PLACE_ID,USER_ID,PLACE_NAME,PLACE_TYPE,ADDRESS,LATITUDE,LONGITUDE,ALLOW_STATUS,HAS_WIDE_TABLE,HAS_OUTLET,IS_QUIET,NO_TIME_LIMIT,HAS_MANY_SEATS,NO_MIN_ORDER,HAS_PARKING,IS_24HOURS,HAS_OUTDOOR,PET_FRIENDLY,HAS_FOOD,HAS_RESTROOM,PLACE_IMG,CREATED_AT,UPDATED_AT) values (11,1,'스타벅스 부평점','카페','인천광역시 부평구 부평대로 1',37.4899,126.7235,'허용','Y','Y','N','N','N','N','N','N','N','N','N','Y',null,to_timestamp('26/06/01 15:24:38.592000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 15:24:38.592000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACES (PLACE_ID,USER_ID,PLACE_NAME,PLACE_TYPE,ADDRESS,LATITUDE,LONGITUDE,ALLOW_STATUS,HAS_WIDE_TABLE,HAS_OUTLET,IS_QUIET,NO_TIME_LIMIT,HAS_MANY_SEATS,NO_MIN_ORDER,HAS_PARKING,IS_24HOURS,HAS_OUTDOOR,PET_FRIENDLY,HAS_FOOD,HAS_RESTROOM,PLACE_IMG,CREATED_AT,UPDATED_AT) values (12,1,'이디야 인천터미널점','카페','인천광역시 남동구 인주대로 581',37.4473,126.7054,'금지','N','N','N','N','Y','N','N','N','N','N','N','Y',null,to_timestamp('26/06/01 15:24:38.598000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 15:24:38.598000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACES (PLACE_ID,USER_ID,PLACE_NAME,PLACE_TYPE,ADDRESS,LATITUDE,LONGITUDE,ALLOW_STATUS,HAS_WIDE_TABLE,HAS_OUTLET,IS_QUIET,NO_TIME_LIMIT,HAS_MANY_SEATS,NO_MIN_ORDER,HAS_PARKING,IS_24HOURS,HAS_OUTDOOR,PET_FRIENDLY,HAS_FOOD,HAS_RESTROOM,PLACE_IMG,CREATED_AT,UPDATED_AT) values (13,1,'카페 달달 송도점','카페','인천광역시 연수구 송도동 24-5',37.383,126.6564,'허용','Y','Y','Y','Y','Y','N','N','N','N','N','N','Y',null,to_timestamp('26/06/01 15:24:38.604000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 15:24:38.604000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACES (PLACE_ID,USER_ID,PLACE_NAME,PLACE_TYPE,ADDRESS,LATITUDE,LONGITUDE,ALLOW_STATUS,HAS_WIDE_TABLE,HAS_OUTLET,IS_QUIET,NO_TIME_LIMIT,HAS_MANY_SEATS,NO_MIN_ORDER,HAS_PARKING,IS_24HOURS,HAS_OUTDOOR,PET_FRIENDLY,HAS_FOOD,HAS_RESTROOM,PLACE_IMG,CREATED_AT,UPDATED_AT) values (15,1,'북카페 책마을 강화점','도서관','인천광역시 강화군 강화읍 중앙로 10',37.7478,126.4878,'허용','Y','N','Y','Y','Y','N','N','N','N','N','N','Y',null,to_timestamp('26/06/01 15:24:38.629000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 15:24:38.629000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACES (PLACE_ID,USER_ID,PLACE_NAME,PLACE_TYPE,ADDRESS,LATITUDE,LONGITUDE,ALLOW_STATUS,HAS_WIDE_TABLE,HAS_OUTLET,IS_QUIET,NO_TIME_LIMIT,HAS_MANY_SEATS,NO_MIN_ORDER,HAS_PARKING,IS_24HOURS,HAS_OUTDOOR,PET_FRIENDLY,HAS_FOOD,HAS_RESTROOM,PLACE_IMG,CREATED_AT,UPDATED_AT) values (16,1,'메가커피 계양점','카페','인천광역시 계양구 계산로 10',37.5374,126.7382,'금지','N','N','N','N','Y','N','N','N','N','N','N','N',null,to_timestamp('26/06/01 15:24:38.634000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 15:24:38.634000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACES (PLACE_ID,USER_ID,PLACE_NAME,PLACE_TYPE,ADDRESS,LATITUDE,LONGITUDE,ALLOW_STATUS,HAS_WIDE_TABLE,HAS_OUTLET,IS_QUIET,NO_TIME_LIMIT,HAS_MANY_SEATS,NO_MIN_ORDER,HAS_PARKING,IS_24HOURS,HAS_OUTDOOR,PET_FRIENDLY,HAS_FOOD,HAS_RESTROOM,PLACE_IMG,CREATED_AT,UPDATED_AT) values (17,1,'스타벅스 수원역점','카페','경기도 수원시 팔달구 덕영대로 924',37.2653,127.0005,'허용','Y','Y','N','N','Y','N','N','N','N','N','N','Y',null,to_timestamp('26/06/01 15:24:38.648000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 15:24:38.648000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACES (PLACE_ID,USER_ID,PLACE_NAME,PLACE_TYPE,ADDRESS,LATITUDE,LONGITUDE,ALLOW_STATUS,HAS_WIDE_TABLE,HAS_OUTLET,IS_QUIET,NO_TIME_LIMIT,HAS_MANY_SEATS,NO_MIN_ORDER,HAS_PARKING,IS_24HOURS,HAS_OUTDOOR,PET_FRIENDLY,HAS_FOOD,HAS_RESTROOM,PLACE_IMG,CREATED_AT,UPDATED_AT) values (18,1,'이디야 성남판교점','카페','경기도 성남시 분당구 판교역로 146',37.3948,127.1112,'금지','N','N','N','N','N','N','N','N','N','N','N','Y',null,to_timestamp('26/06/01 15:24:38.653000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 15:24:38.653000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACES (PLACE_ID,USER_ID,PLACE_NAME,PLACE_TYPE,ADDRESS,LATITUDE,LONGITUDE,ALLOW_STATUS,HAS_WIDE_TABLE,HAS_OUTLET,IS_QUIET,NO_TIME_LIMIT,HAS_MANY_SEATS,NO_MIN_ORDER,HAS_PARKING,IS_24HOURS,HAS_OUTDOOR,PET_FRIENDLY,HAS_FOOD,HAS_RESTROOM,PLACE_IMG,CREATED_AT,UPDATED_AT) values (19,1,'카페 온더테이블 용인점','카페','경기도 용인시 기흥구 동백죽전대로 16',37.2681,127.119,'허용','Y','Y','Y','Y','Y','N','N','N','N','Y','N','Y',null,to_timestamp('26/06/01 15:24:38.658000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 15:24:38.658000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACES (PLACE_ID,USER_ID,PLACE_NAME,PLACE_TYPE,ADDRESS,LATITUDE,LONGITUDE,ALLOW_STATUS,HAS_WIDE_TABLE,HAS_OUTLET,IS_QUIET,NO_TIME_LIMIT,HAS_MANY_SEATS,NO_MIN_ORDER,HAS_PARKING,IS_24HOURS,HAS_OUTDOOR,PET_FRIENDLY,HAS_FOOD,HAS_RESTROOM,PLACE_IMG,CREATED_AT,UPDATED_AT) values (21,1,'할리스 의정부점','카페','경기도 의정부시 의정부동 산10-1',37.7381,127.0472,'허용','Y','N','Y','Y','Y','N','N','N','N','N','N','Y',null,to_timestamp('26/06/01 15:24:38.685000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 15:24:38.685000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACES (PLACE_ID,USER_ID,PLACE_NAME,PLACE_TYPE,ADDRESS,LATITUDE,LONGITUDE,ALLOW_STATUS,HAS_WIDE_TABLE,HAS_OUTLET,IS_QUIET,NO_TIME_LIMIT,HAS_MANY_SEATS,NO_MIN_ORDER,HAS_PARKING,IS_24HOURS,HAS_OUTDOOR,PET_FRIENDLY,HAS_FOOD,HAS_RESTROOM,PLACE_IMG,CREATED_AT,UPDATED_AT) values (22,1,'빽다방 안양점','카페','경기도 안양시 만안구 안양로 10',37.3943,126.9568,'금지','N','N','N','N','Y','N','N','N','N','N','N','Y',null,to_timestamp('26/06/01 15:24:38.691000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 15:24:38.691000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACES (PLACE_ID,USER_ID,PLACE_NAME,PLACE_TYPE,ADDRESS,LATITUDE,LONGITUDE,ALLOW_STATUS,HAS_WIDE_TABLE,HAS_OUTLET,IS_QUIET,NO_TIME_LIMIT,HAS_MANY_SEATS,NO_MIN_ORDER,HAS_PARKING,IS_24HOURS,HAS_OUTDOOR,PET_FRIENDLY,HAS_FOOD,HAS_RESTROOM,PLACE_IMG,CREATED_AT,UPDATED_AT) values (23,1,'카페 소담 광주점','카페','경기도 광주시 경안로 10',37.4296,127.2553,'허용','Y','Y','Y','Y','N','N','N','N','N','N','N','Y',null,to_timestamp('26/06/01 15:24:38.697000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 15:24:38.697000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACES (PLACE_ID,USER_ID,PLACE_NAME,PLACE_TYPE,ADDRESS,LATITUDE,LONGITUDE,ALLOW_STATUS,HAS_WIDE_TABLE,HAS_OUTLET,IS_QUIET,NO_TIME_LIMIT,HAS_MANY_SEATS,NO_MIN_ORDER,HAS_PARKING,IS_24HOURS,HAS_OUTDOOR,PET_FRIENDLY,HAS_FOOD,HAS_RESTROOM,PLACE_IMG,CREATED_AT,UPDATED_AT) values (24,1,'구월 로데오 파스쿠찌','카페','인천 남동구 구월동 1463-2',37.4448541,126.7014931,'허용','Y','Y','N','N','Y','N','N','N','N','N','N','Y',null,to_timestamp('26/06/01 16:15:15.555000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 16:15:15.555000000','RR/MM/DD HH24:MI:SSXFF'));
REM INSERTING into MOYEODDUGI.PLACE_REVIEWS
SET DEFINE OFF;
Insert into MOYEODDUGI.PLACE_REVIEWS (REVIEW_ID,PLACE_ID,USER_ID,CONTENT,ALLOW_STATUS,REVIEW_IMG,CREATED_AT,UPDATED_AT) values (13,24,1,'테이블도 엄청 많고 3층이라서 좋습니다. ㅎㅎ','허용',null,to_timestamp('26/06/01 16:54:29.811000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 16:54:29.811000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACE_REVIEWS (REVIEW_ID,PLACE_ID,USER_ID,CONTENT,ALLOW_STATUS,REVIEW_IMG,CREATED_AT,UPDATED_AT) values (19,24,1,'딱히 막지 않는거 같아요','모르겠어요',null,to_timestamp('26/06/01 16:57:23.269000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 16:57:23.269000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACE_REVIEWS (REVIEW_ID,PLACE_ID,USER_ID,CONTENT,ALLOW_STATUS,REVIEW_IMG,CREATED_AT,UPDATED_AT) values (11,24,1,'거의 매일 가고 있어요','허용',null,to_timestamp('26/06/01 16:50:30.212000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 16:50:30.212000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACE_REVIEWS (REVIEW_ID,PLACE_ID,USER_ID,CONTENT,ALLOW_STATUS,REVIEW_IMG,CREATED_AT,UPDATED_AT) values (20,24,1,'저는 금지 당했습니다 ㅠㅠ','금지',null,to_timestamp('26/06/01 16:57:42.979000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 16:57:42.979000000','RR/MM/DD HH24:MI:SSXFF'));
REM INSERTING into MOYEODDUGI.POSTS
SET DEFINE OFF;
Insert into MOYEODDUGI.POSTS (POST_ID,USER_ID,BOARD_TYPE,TITLE,CONTENT,VIEW_COUNT,GATHER_STATUS,GATHER_COUNT,CREATED_AT,UPDATED_AT) values (1,1,'자유','첫 번째 자유 게시글','안녕하세요! 뜨개질 시작한 지 얼마 안 됐어요 😊',2,null,null,to_timestamp('26/05/30 14:04:08.375000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/05/30 14:34:25.956000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.POSTS (POST_ID,USER_ID,BOARD_TYPE,TITLE,CONTENT,VIEW_COUNT,GATHER_STATUS,GATHER_COUNT,CREATED_AT,UPDATED_AT) values (2,1,'질문','코바늘 기초 질문이요!','한길긴뜨기랑 긴뜨기 차이가 뭔가요?',0,null,null,to_timestamp('26/05/30 14:04:08.386000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/05/30 14:04:08.386000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.POSTS (POST_ID,USER_ID,BOARD_TYPE,TITLE,CONTENT,VIEW_COUNT,GATHER_STATUS,GATHER_COUNT,CREATED_AT,UPDATED_AT) values (7,1,'자유','오늘 카페에서 뜨개질 했어요!','부평 스타벅스에서 3시간 뜨개질 ㅎㅎ',0,null,null,to_timestamp('26/05/30 14:59:47.683000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/05/30 14:59:47.683000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.POSTS (POST_ID,USER_ID,BOARD_TYPE,TITLE,CONTENT,VIEW_COUNT,GATHER_STATUS,GATHER_COUNT,CREATED_AT,UPDATED_AT) values (11,1,'자유','첫 작품 완성했어요!!','드디어 곰돌이 인형 완성 ㅠㅠ 너무 뿌듯해요',0,null,null,to_timestamp('26/05/30 14:59:47.743000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/05/30 14:59:47.743000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.POSTS (POST_ID,USER_ID,BOARD_TYPE,TITLE,CONTENT,VIEW_COUNT,GATHER_STATUS,GATHER_COUNT,CREATED_AT,UPDATED_AT) values (12,1,'질문','실 엉킨거 푸는 팁 있나요?','뜨다가 실이 너무 엉켜서 힘드네요 ㅠㅠ',0,null,null,to_timestamp('26/05/30 14:59:47.747000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/05/30 14:59:47.747000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.POSTS (POST_ID,USER_ID,BOARD_TYPE,TITLE,CONTENT,VIEW_COUNT,GATHER_STATUS,GATHER_COUNT,CREATED_AT,UPDATED_AT) values (21,21,'자유','고양이 보닛 ㅎㅎ','너무 귀엽죠 ㅋㅋㅋ 저희집 고양이 하루입니다. ',0,null,null,to_timestamp('26/06/02 14:28:50.329000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/02 14:28:50.329000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.POSTS (POST_ID,USER_ID,BOARD_TYPE,TITLE,CONTENT,VIEW_COUNT,GATHER_STATUS,GATHER_COUNT,CREATED_AT,UPDATED_AT) values (25,41,'자유','2장을 올리면?','어떻게 나오나요?',0,null,null,to_timestamp('26/06/02 14:57:01.290000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/02 14:57:01.290000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.POSTS (POST_ID,USER_ID,BOARD_TYPE,TITLE,CONTENT,VIEW_COUNT,GATHER_STATUS,GATHER_COUNT,CREATED_AT,UPDATED_AT) values (13,1,'자유','가입인사','가입했어요 ㅎ',0,null,null,to_timestamp('26/06/01 10:08:26.614000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 10:08:26.614000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.POSTS (POST_ID,USER_ID,BOARD_TYPE,TITLE,CONTENT,VIEW_COUNT,GATHER_STATUS,GATHER_COUNT,CREATED_AT,UPDATED_AT) values (24,41,'자유','3장을 올리면?','어떻게 되나요',0,null,null,to_timestamp('26/06/02 14:53:24.420000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/02 14:53:24.420000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.POSTS (POST_ID,USER_ID,BOARD_TYPE,TITLE,CONTENT,VIEW_COUNT,GATHER_STATUS,GATHER_COUNT,CREATED_AT,UPDATED_AT) values (22,41,'자유','가방 떴어요','가방 멋지죠 ㅎㅎ ',0,null,null,to_timestamp('26/06/02 14:48:55.090000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/02 14:48:55.090000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.POSTS (POST_ID,USER_ID,BOARD_TYPE,TITLE,CONTENT,VIEW_COUNT,GATHER_STATUS,GATHER_COUNT,CREATED_AT,UPDATED_AT) values (23,41,'자유','이미지가 등록이 안되나요','멋진 곰가족 ',0,null,null,to_timestamp('26/06/02 14:50:38.108000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/02 14:50:38.108000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.POSTS (POST_ID,USER_ID,BOARD_TYPE,TITLE,CONTENT,VIEW_COUNT,GATHER_STATUS,GATHER_COUNT,CREATED_AT,UPDATED_AT) values (26,41,'자유',null,'다들 요즘 뭐 뜨시나요 ??',0,null,null,to_timestamp('26/06/02 15:51:08.721000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/02 15:51:08.721000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.POSTS (POST_ID,USER_ID,BOARD_TYPE,TITLE,CONTENT,VIEW_COUNT,GATHER_STATUS,GATHER_COUNT,CREATED_AT,UPDATED_AT) values (27,41,'자유',null,'귀엽지 않나요 멍멍 ',0,null,null,to_timestamp('26/06/02 15:52:23.663000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/02 15:52:23.663000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.POSTS (POST_ID,USER_ID,BOARD_TYPE,TITLE,CONTENT,VIEW_COUNT,GATHER_STATUS,GATHER_COUNT,CREATED_AT,UPDATED_AT) values (28,41,'자유',null,'뉴 도안들 ...조만간 업로드 예정..',0,null,null,to_timestamp('26/06/02 15:52:48.286000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/02 15:52:48.286000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.POSTS (POST_ID,USER_ID,BOARD_TYPE,TITLE,CONTENT,VIEW_COUNT,GATHER_STATUS,GATHER_COUNT,CREATED_AT,UPDATED_AT) values (30,41,'작품자랑','손 부숴지는줄 알았습니다. 역작이에요.','정말 오래 걸렸던... 저의 첫 코바늘 가디건 입니다!!
주머니도 만들고 엄청 만족 스러워요.
안감을 달아주면 더 멋질 거 같은데 집에 재봉틀이 없어서 거기까진.. 또르륵...',0,null,null,to_timestamp('26/06/02 17:03:44.649000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/02 17:03:44.649000000','RR/MM/DD HH24:MI:SSXFF'));
REM INSERTING into MOYEODDUGI.POST_IMAGES
SET DEFINE OFF;
Insert into MOYEODDUGI.POST_IMAGES (IMAGE_ID,POST_ID,IMAGE_URL,IS_THUMBNAIL,SORT_ORDER,CREATED_AT) values (1,21,'/uploads/posts/post_1780378130310_spopphtug.jpg','Y',0,to_timestamp('26/06/02 14:28:50.339000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.POST_IMAGES (IMAGE_ID,POST_ID,IMAGE_URL,IS_THUMBNAIL,SORT_ORDER,CREATED_AT) values (7,25,'/uploads/posts/post_1780379821257_3eot0d3vs.jpg','Y',0,to_timestamp('26/06/02 14:57:01.293000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.POST_IMAGES (IMAGE_ID,POST_ID,IMAGE_URL,IS_THUMBNAIL,SORT_ORDER,CREATED_AT) values (8,25,'/uploads/posts/post_1780379821277_dsgcoi44p.jpg','N',1,to_timestamp('26/06/02 14:57:01.294000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.POST_IMAGES (IMAGE_ID,POST_ID,IMAGE_URL,IS_THUMBNAIL,SORT_ORDER,CREATED_AT) values (2,22,'/uploads/posts/post_1780379335080_52xcjuchv.jpg','Y',0,to_timestamp('26/06/02 14:48:55.093000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.POST_IMAGES (IMAGE_ID,POST_ID,IMAGE_URL,IS_THUMBNAIL,SORT_ORDER,CREATED_AT) values (3,23,'/uploads/posts/post_1780379438083_n3ty5exei.jpg','Y',0,to_timestamp('26/06/02 14:50:38.109000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.POST_IMAGES (IMAGE_ID,POST_ID,IMAGE_URL,IS_THUMBNAIL,SORT_ORDER,CREATED_AT) values (4,24,'/uploads/posts/post_1780379604401_x8fv0n1lu.jpg','Y',0,to_timestamp('26/06/02 14:53:24.422000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.POST_IMAGES (IMAGE_ID,POST_ID,IMAGE_URL,IS_THUMBNAIL,SORT_ORDER,CREATED_AT) values (5,24,'/uploads/posts/post_1780379604406_77qc6ozfw.jpg','N',1,to_timestamp('26/06/02 14:53:24.422000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.POST_IMAGES (IMAGE_ID,POST_ID,IMAGE_URL,IS_THUMBNAIL,SORT_ORDER,CREATED_AT) values (6,24,'/uploads/posts/post_1780379604413_dpmnatj9p.jpg','N',2,to_timestamp('26/06/02 14:53:24.423000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.POST_IMAGES (IMAGE_ID,POST_ID,IMAGE_URL,IS_THUMBNAIL,SORT_ORDER,CREATED_AT) values (9,27,'/uploads/posts/post_1780383143664_0.jpg','Y',0,to_timestamp('26/06/02 15:52:23.671000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.POST_IMAGES (IMAGE_ID,POST_ID,IMAGE_URL,IS_THUMBNAIL,SORT_ORDER,CREATED_AT) values (10,28,'/uploads/posts/post_1780383168287_0.jpg','Y',0,to_timestamp('26/06/02 15:52:48.291000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.POST_IMAGES (IMAGE_ID,POST_ID,IMAGE_URL,IS_THUMBNAIL,SORT_ORDER,CREATED_AT) values (11,28,'/uploads/posts/post_1780383168292_1.jpg','N',1,to_timestamp('26/06/02 15:52:48.318000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.POST_IMAGES (IMAGE_ID,POST_ID,IMAGE_URL,IS_THUMBNAIL,SORT_ORDER,CREATED_AT) values (12,28,'/uploads/posts/post_1780383168319_2.jpg','N',2,to_timestamp('26/06/02 15:52:48.347000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.POST_IMAGES (IMAGE_ID,POST_ID,IMAGE_URL,IS_THUMBNAIL,SORT_ORDER,CREATED_AT) values (13,30,'/uploads/posts/post_1780387424649_0.jpg','Y',0,to_timestamp('26/06/02 17:03:44.770000000','RR/MM/DD HH24:MI:SSXFF'));
REM INSERTING into MOYEODDUGI.SCRAPS
SET DEFINE OFF;
REM INSERTING into MOYEODDUGI.USERS
SET DEFINE OFF;
Insert into MOYEODDUGI.USERS (USER_ID,EMAIL,PASSWORD,SOCIAL_PROVIDER,SOCIAL_ID,NICKNAME,PROFILE_IMG,BIO,USER_ROLE,STATUS,CREATED_AT,UPDATED_AT,USER_NAME,BIRTH_DATE) values (1,'test@test.com','$2b$10$8AuuQOHiXqBsllXUcagfgO40j6Xcz6KNQMQNY0R50x0PaABv/o2xu',null,null,'뜨개중독',null,null,'USER','ACTIVE',to_timestamp('26/05/29 15:12:57.899000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/05/29 15:12:57.899000000','RR/MM/DD HH24:MI:SSXFF'),'테스트',null);
Insert into MOYEODDUGI.USERS (USER_ID,EMAIL,PASSWORD,SOCIAL_PROVIDER,SOCIAL_ID,NICKNAME,PROFILE_IMG,BIO,USER_ROLE,STATUS,CREATED_AT,UPDATED_AT,USER_NAME,BIRTH_DATE) values (2,'wahaha@nate.com','$2b$10$3YO/j6dGDtDBOxJgK2om9ObbgzI6tFTKf9OicQ9zbUzRshqEZozze',null,null,'코뜨는치와와',null,null,'USER','ACTIVE',to_timestamp('26/05/29 16:10:38.748000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/05/29 16:10:38.748000000','RR/MM/DD HH24:MI:SSXFF'),'김하나',null);
Insert into MOYEODDUGI.USERS (USER_ID,EMAIL,PASSWORD,SOCIAL_PROVIDER,SOCIAL_ID,NICKNAME,PROFILE_IMG,BIO,USER_ROLE,STATUS,CREATED_AT,UPDATED_AT,USER_NAME,BIRTH_DATE) values (21,'hiru@naver.com','$2b$10$pgX9kPFMMAcCdbjmc/LW..V9aQjfLAduh697euz7XcmMo9LUKsMTW',null,null,'하루의하루','/uploads/profiles/profile_1780368611361.jpg','하루의 하루','USER','ACTIVE',to_timestamp('26/06/01 09:39:08.960000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/02 11:50:11.373000000','RR/MM/DD HH24:MI:SSXFF'),'이하루',null);
Insert into MOYEODDUGI.USERS (USER_ID,EMAIL,PASSWORD,SOCIAL_PROVIDER,SOCIAL_ID,NICKNAME,PROFILE_IMG,BIO,USER_ROLE,STATUS,CREATED_AT,UPDATED_AT,USER_NAME,BIRTH_DATE) values (41,'datt@naver.com','$2b$10$RytKeFW6Hg0CUu8Hkf5XQedMoXVmJFqySf05CtYQqtUa2k/ZlvsnS',null,null,'다떠베이저','/uploads/profiles/profile_1780378446381.PNG','전부 떠버리겠습니다.','USER','ACTIVE',to_timestamp('26/06/02 14:32:40.287000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/02 14:34:06.410000000','RR/MM/DD HH24:MI:SSXFF'),'김단',null);
--------------------------------------------------------
--  DDL for Index UQ_CHAT_MEMBERS
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOYEODDUGI"."UQ_CHAT_MEMBERS" ON "MOYEODDUGI"."CHAT_MEMBERS" ("ROOM_ID", "USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_CHAT_ROOM_POST
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOYEODDUGI"."UQ_CHAT_ROOM_POST" ON "MOYEODDUGI"."CHAT_ROOMS" ("POST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_FOLLOWS
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOYEODDUGI"."UQ_FOLLOWS" ON "MOYEODDUGI"."FOLLOWS" ("FOLLOWER_ID", "FOLLOWING_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_LIKES
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOYEODDUGI"."UQ_LIKES" ON "MOYEODDUGI"."LIKES" ("USER_ID", "TARGET_TYPE", "TARGET_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_SCRAPS
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOYEODDUGI"."UQ_SCRAPS" ON "MOYEODDUGI"."SCRAPS" ("USER_ID", "TARGET_TYPE", "TARGET_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_USERS_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOYEODDUGI"."UQ_USERS_EMAIL" ON "MOYEODDUGI"."USERS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_USERS_NICKNAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOYEODDUGI"."UQ_USERS_NICKNAME" ON "MOYEODDUGI"."USERS" ("NICKNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRG_COMMENTS_UPDATED_AT
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "MOYEODDUGI"."TRG_COMMENTS_UPDATED_AT" 
    BEFORE UPDATE ON comments
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "MOYEODDUGI"."TRG_COMMENTS_UPDATED_AT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_PATTERNS_UPDATED_AT
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "MOYEODDUGI"."TRG_PATTERNS_UPDATED_AT" 
    BEFORE UPDATE ON patterns
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "MOYEODDUGI"."TRG_PATTERNS_UPDATED_AT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_PLACES_UPDATED_AT
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "MOYEODDUGI"."TRG_PLACES_UPDATED_AT" 
    BEFORE UPDATE ON places
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "MOYEODDUGI"."TRG_PLACES_UPDATED_AT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_PLACE_REVIEWS_UPDATED_AT
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "MOYEODDUGI"."TRG_PLACE_REVIEWS_UPDATED_AT" 
    BEFORE UPDATE ON place_reviews
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "MOYEODDUGI"."TRG_PLACE_REVIEWS_UPDATED_AT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_POSTS_UPDATED_AT
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "MOYEODDUGI"."TRG_POSTS_UPDATED_AT" 
    BEFORE UPDATE ON posts
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "MOYEODDUGI"."TRG_POSTS_UPDATED_AT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_USERS_UPDATED_AT
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "MOYEODDUGI"."TRG_USERS_UPDATED_AT" 
    BEFORE UPDATE ON users
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "MOYEODDUGI"."TRG_USERS_UPDATED_AT" ENABLE;
--------------------------------------------------------
--  Constraints for Table CHAT_ROOMS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."CHAT_ROOMS" MODIFY ("ROOM_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."CHAT_ROOMS" MODIFY ("POST_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."CHAT_ROOMS" MODIFY ("ROOM_NAME" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."CHAT_ROOMS" MODIFY ("MAX_MEMBERS" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."CHAT_ROOMS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."CHAT_ROOMS" ADD PRIMARY KEY ("ROOM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MOYEODDUGI"."CHAT_ROOMS" ADD CONSTRAINT "UQ_CHAT_ROOM_POST" UNIQUE ("POST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PATTERNS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."PATTERNS" MODIFY ("PATTERN_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PATTERNS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PATTERNS" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PATTERNS" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PATTERNS" MODIFY ("NEEDLE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PATTERNS" MODIFY ("DIFFICULTY" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PATTERNS" MODIFY ("VIEW_COUNT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PATTERNS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PATTERNS" MODIFY ("UPDATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PATTERNS" ADD CONSTRAINT "CHK_NEEDLE_TYPE" CHECK (needle_type IN ('코바늘', '대바늘')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."PATTERNS" ADD CONSTRAINT "CHK_DIFFICULTY" CHECK (difficulty IN ('입문', '초급', '중급', '고급')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."PATTERNS" ADD PRIMARY KEY ("PATTERN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MOYEODDUGI"."PATTERNS" ADD CONSTRAINT "CHK_PATTERN_CATEGORY" CHECK (category IN ('소품', '가방', '모자', '의류', '인형', '선물용', '기타')) ENABLE;
--------------------------------------------------------
--  Constraints for Table PATTERN_TAGS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."PATTERN_TAGS" MODIFY ("TAG_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PATTERN_TAGS" MODIFY ("PATTERN_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PATTERN_TAGS" MODIFY ("TAG_NAME" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PATTERN_TAGS" ADD PRIMARY KEY ("TAG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CHAT_MEMBERS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."CHAT_MEMBERS" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."CHAT_MEMBERS" MODIFY ("ROOM_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."CHAT_MEMBERS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."CHAT_MEMBERS" MODIFY ("IS_HOST" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."CHAT_MEMBERS" MODIFY ("JOINED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."CHAT_MEMBERS" ADD CONSTRAINT "CHK_IS_HOST" CHECK (is_host IN ('Y', 'N')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."CHAT_MEMBERS" ADD PRIMARY KEY ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MOYEODDUGI"."CHAT_MEMBERS" ADD CONSTRAINT "UQ_CHAT_MEMBERS" UNIQUE ("ROOM_ID", "USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."USERS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."USERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."USERS" MODIFY ("NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."USERS" MODIFY ("USER_ROLE" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."USERS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."USERS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."USERS" MODIFY ("UPDATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."USERS" ADD CONSTRAINT "CHK_USER_ROLE" CHECK (user_role IN ('USER', 'ADMIN')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."USERS" ADD CONSTRAINT "CHK_USER_STATUS" CHECK (status IN ('ACTIVE', 'INACTIVE', 'BANNED')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."USERS" ADD CONSTRAINT "CHK_SOCIAL_PROVIDER" CHECK (social_provider IN ('KAKAO', 'GOOGLE') 
                                          OR social_provider IS NULL) ENABLE;
  ALTER TABLE "MOYEODDUGI"."USERS" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MOYEODDUGI"."USERS" ADD CONSTRAINT "UQ_USERS_EMAIL" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MOYEODDUGI"."USERS" ADD CONSTRAINT "UQ_USERS_NICKNAME" UNIQUE ("NICKNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PLACES
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("PLACE_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("PLACE_NAME" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("PLACE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("LATITUDE" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("LONGITUDE" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("ALLOW_STATUS" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("HAS_WIDE_TABLE" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("HAS_OUTLET" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("IS_QUIET" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("NO_TIME_LIMIT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("HAS_MANY_SEATS" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("NO_MIN_ORDER" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("HAS_PARKING" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("IS_24HOURS" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("HAS_OUTDOOR" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("PET_FRIENDLY" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("HAS_FOOD" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("HAS_RESTROOM" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("UPDATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" ADD CONSTRAINT "CHK_PLACE_TYPE" CHECK (place_type IN ('카페', '도서관', '공원', '기타')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."PLACES" ADD CONSTRAINT "CHK_ALLOW_STATUS" CHECK (allow_status IN ('허용', '묵인', '금지', '모르겠어요')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."PLACES" ADD CONSTRAINT "CHK_WIDE_TABLE" CHECK (has_wide_table IN ('Y', 'N')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."PLACES" ADD CONSTRAINT "CHK_OUTLET" CHECK (has_outlet IN ('Y', 'N')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."PLACES" ADD CONSTRAINT "CHK_QUIET" CHECK (is_quiet IN ('Y', 'N')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."PLACES" ADD CONSTRAINT "CHK_TIME_LIMIT" CHECK (no_time_limit IN ('Y', 'N')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."PLACES" ADD CONSTRAINT "CHK_MANY_SEATS" CHECK (has_many_seats IN ('Y', 'N')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."PLACES" ADD CONSTRAINT "CHK_MIN_ORDER" CHECK (no_min_order IN ('Y', 'N')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."PLACES" ADD CONSTRAINT "CHK_PARKING" CHECK (has_parking IN ('Y', 'N')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."PLACES" ADD CONSTRAINT "CHK_24HOURS" CHECK (is_24hours IN ('Y', 'N')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."PLACES" ADD CONSTRAINT "CHK_OUTDOOR" CHECK (has_outdoor IN ('Y', 'N')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."PLACES" ADD CONSTRAINT "CHK_PET" CHECK (pet_friendly IN ('Y', 'N')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."PLACES" ADD CONSTRAINT "CHK_FOOD" CHECK (has_food IN ('Y', 'N')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."PLACES" ADD CONSTRAINT "CHK_RESTROOM" CHECK (has_restroom IN ('Y', 'N')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."PLACES" ADD PRIMARY KEY ("PLACE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table POST_IMAGES
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."POST_IMAGES" MODIFY ("IMAGE_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."POST_IMAGES" MODIFY ("POST_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."POST_IMAGES" MODIFY ("IMAGE_URL" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."POST_IMAGES" MODIFY ("IS_THUMBNAIL" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."POST_IMAGES" MODIFY ("SORT_ORDER" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."POST_IMAGES" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."POST_IMAGES" ADD CONSTRAINT "CHK_THUMBNAIL" CHECK (is_thumbnail IN ('Y', 'N')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."POST_IMAGES" ADD PRIMARY KEY ("IMAGE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMMENTS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."COMMENTS" MODIFY ("COMMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."COMMENTS" MODIFY ("TARGET_TYPE" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."COMMENTS" MODIFY ("TARGET_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."COMMENTS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."COMMENTS" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."COMMENTS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."COMMENTS" MODIFY ("UPDATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."COMMENTS" ADD CONSTRAINT "CHK_COMMENT_TARGET" CHECK (target_type IN ('POST', 'PATTERN')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."COMMENTS" ADD PRIMARY KEY ("COMMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LIKES
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."LIKES" MODIFY ("LIKE_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."LIKES" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."LIKES" MODIFY ("TARGET_TYPE" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."LIKES" MODIFY ("TARGET_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."LIKES" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."LIKES" ADD CONSTRAINT "CHK_LIKES_TYPE" CHECK (target_type IN ('POST', 'PATTERN')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."LIKES" ADD PRIMARY KEY ("LIKE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MOYEODDUGI"."LIKES" ADD CONSTRAINT "UQ_LIKES" UNIQUE ("USER_ID", "TARGET_TYPE", "TARGET_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table POSTS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."POSTS" MODIFY ("POST_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."POSTS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."POSTS" MODIFY ("BOARD_TYPE" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."POSTS" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."POSTS" MODIFY ("VIEW_COUNT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."POSTS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."POSTS" MODIFY ("UPDATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."POSTS" ADD CONSTRAINT "CHK_BOARD_TYPE" CHECK (board_type IN 
                                    ('자유', '질문', '모여떠요', '떠주세요', '떠드려요', '작품자랑')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."POSTS" ADD CONSTRAINT "CHK_GATHER_STATUS" CHECK (gather_status IN ('모집중', '마감') 
                                          OR gather_status IS NULL) ENABLE;
  ALTER TABLE "MOYEODDUGI"."POSTS" ADD PRIMARY KEY ("POST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SCRAPS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."SCRAPS" MODIFY ("SCRAP_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."SCRAPS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."SCRAPS" MODIFY ("TARGET_TYPE" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."SCRAPS" MODIFY ("TARGET_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."SCRAPS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."SCRAPS" ADD CONSTRAINT "CHK_SCRAPS_TYPE" CHECK (target_type IN ('PATTERN', 'POST')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."SCRAPS" ADD PRIMARY KEY ("SCRAP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MOYEODDUGI"."SCRAPS" ADD CONSTRAINT "UQ_SCRAPS" UNIQUE ("USER_ID", "TARGET_TYPE", "TARGET_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PATTERN_IMAGES
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."PATTERN_IMAGES" MODIFY ("IMAGE_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PATTERN_IMAGES" MODIFY ("PATTERN_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PATTERN_IMAGES" MODIFY ("IMAGE_URL" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PATTERN_IMAGES" MODIFY ("SORT_ORDER" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PATTERN_IMAGES" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PATTERN_IMAGES" ADD PRIMARY KEY ("IMAGE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PLACE_REVIEWS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."PLACE_REVIEWS" MODIFY ("REVIEW_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACE_REVIEWS" MODIFY ("PLACE_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACE_REVIEWS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACE_REVIEWS" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACE_REVIEWS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACE_REVIEWS" MODIFY ("UPDATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACE_REVIEWS" ADD CONSTRAINT "CHK_REVIEW_ALLOW" CHECK (allow_status IN ('허용', '묵인', '금지', '모르겠어요')
                                          OR allow_status IS NULL) ENABLE;
  ALTER TABLE "MOYEODDUGI"."PLACE_REVIEWS" ADD PRIMARY KEY ("REVIEW_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FOLLOWS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."FOLLOWS" MODIFY ("FOLLOW_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."FOLLOWS" MODIFY ("FOLLOWER_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."FOLLOWS" MODIFY ("FOLLOWING_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."FOLLOWS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."FOLLOWS" ADD CONSTRAINT "CHK_FOLLOWS_SELF" CHECK (follower_id != following_id) ENABLE;
  ALTER TABLE "MOYEODDUGI"."FOLLOWS" ADD PRIMARY KEY ("FOLLOW_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MOYEODDUGI"."FOLLOWS" ADD CONSTRAINT "UQ_FOLLOWS" UNIQUE ("FOLLOWER_ID", "FOLLOWING_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CHAT_MESSAGES
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."CHAT_MESSAGES" MODIFY ("MESSAGE_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."CHAT_MESSAGES" MODIFY ("ROOM_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."CHAT_MESSAGES" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."CHAT_MESSAGES" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."CHAT_MESSAGES" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."CHAT_MESSAGES" ADD PRIMARY KEY ("MESSAGE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table NOTIFICATIONS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."NOTIFICATIONS" MODIFY ("NOTI_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."NOTIFICATIONS" MODIFY ("RECEIVER_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."NOTIFICATIONS" MODIFY ("NOTI_TYPE" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."NOTIFICATIONS" MODIFY ("MESSAGE" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."NOTIFICATIONS" MODIFY ("IS_READ" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."NOTIFICATIONS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."NOTIFICATIONS" ADD CONSTRAINT "CHK_NOTI_TYPE" CHECK (noti_type IN 
                                    ('NEW_PATTERN', 'COMMENT', 'LIKE', 'FOLLOW', 'GATHER')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."NOTIFICATIONS" ADD CONSTRAINT "CHK_NOTI_READ" CHECK (is_read IN ('Y', 'N')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."NOTIFICATIONS" ADD PRIMARY KEY ("NOTI_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CHAT_MEMBERS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."CHAT_MEMBERS" ADD CONSTRAINT "FK_MEMBER_ROOM" FOREIGN KEY ("ROOM_ID")
	  REFERENCES "MOYEODDUGI"."CHAT_ROOMS" ("ROOM_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "MOYEODDUGI"."CHAT_MEMBERS" ADD CONSTRAINT "FK_MEMBER_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "MOYEODDUGI"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CHAT_MESSAGES
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."CHAT_MESSAGES" ADD CONSTRAINT "FK_MESSAGE_ROOM" FOREIGN KEY ("ROOM_ID")
	  REFERENCES "MOYEODDUGI"."CHAT_ROOMS" ("ROOM_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "MOYEODDUGI"."CHAT_MESSAGES" ADD CONSTRAINT "FK_MESSAGE_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "MOYEODDUGI"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CHAT_ROOMS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."CHAT_ROOMS" ADD CONSTRAINT "FK_ROOM_POST" FOREIGN KEY ("POST_ID")
	  REFERENCES "MOYEODDUGI"."POSTS" ("POST_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMENTS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."COMMENTS" ADD CONSTRAINT "FK_COMMENT_PARENT" FOREIGN KEY ("PARENT_ID")
	  REFERENCES "MOYEODDUGI"."COMMENTS" ("COMMENT_ID") ENABLE;
  ALTER TABLE "MOYEODDUGI"."COMMENTS" ADD CONSTRAINT "FK_COMMENTS_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "MOYEODDUGI"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "MOYEODDUGI"."COMMENTS" ADD CONSTRAINT "FK_COMMENT_REPLY_TO" FOREIGN KEY ("REPLY_TO")
	  REFERENCES "MOYEODDUGI"."COMMENTS" ("COMMENT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FOLLOWS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."FOLLOWS" ADD CONSTRAINT "FK_FOLLOWER" FOREIGN KEY ("FOLLOWER_ID")
	  REFERENCES "MOYEODDUGI"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "MOYEODDUGI"."FOLLOWS" ADD CONSTRAINT "FK_FOLLOWING" FOREIGN KEY ("FOLLOWING_ID")
	  REFERENCES "MOYEODDUGI"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LIKES
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."LIKES" ADD CONSTRAINT "FK_LIKES_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "MOYEODDUGI"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOTIFICATIONS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."NOTIFICATIONS" ADD CONSTRAINT "FK_NOTI_RECEIVER" FOREIGN KEY ("RECEIVER_ID")
	  REFERENCES "MOYEODDUGI"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "MOYEODDUGI"."NOTIFICATIONS" ADD CONSTRAINT "FK_NOTI_SENDER" FOREIGN KEY ("SENDER_ID")
	  REFERENCES "MOYEODDUGI"."USERS" ("USER_ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PATTERNS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."PATTERNS" ADD CONSTRAINT "FK_PATTERNS_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "MOYEODDUGI"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PATTERN_IMAGES
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."PATTERN_IMAGES" ADD CONSTRAINT "FK_PATTERN_IMAGES" FOREIGN KEY ("PATTERN_ID")
	  REFERENCES "MOYEODDUGI"."PATTERNS" ("PATTERN_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PATTERN_TAGS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."PATTERN_TAGS" ADD CONSTRAINT "FK_PATTERN_TAGS" FOREIGN KEY ("PATTERN_ID")
	  REFERENCES "MOYEODDUGI"."PATTERNS" ("PATTERN_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PLACES
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."PLACES" ADD CONSTRAINT "FK_PLACES_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "MOYEODDUGI"."USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PLACE_REVIEWS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."PLACE_REVIEWS" ADD CONSTRAINT "FK_REVIEWS_PLACE" FOREIGN KEY ("PLACE_ID")
	  REFERENCES "MOYEODDUGI"."PLACES" ("PLACE_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "MOYEODDUGI"."PLACE_REVIEWS" ADD CONSTRAINT "FK_REVIEWS_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "MOYEODDUGI"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POSTS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."POSTS" ADD CONSTRAINT "FK_POSTS_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "MOYEODDUGI"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POST_IMAGES
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."POST_IMAGES" ADD CONSTRAINT "FK_POST_IMAGES" FOREIGN KEY ("POST_ID")
	  REFERENCES "MOYEODDUGI"."POSTS" ("POST_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SCRAPS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."SCRAPS" ADD CONSTRAINT "FK_SCRAPS_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "MOYEODDUGI"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
