--------------------------------------------------------
--  파일이 생성됨 - 월요일-6월-01-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CHAT_MEMBERS
--------------------------------------------------------

  CREATE TABLE "MOYEODDUGI"."CHAT_MEMBERS" 
   (	"MEMBER_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ROOM_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"IS_HOST" CHAR(1 BYTE) DEFAULT 'N', 
	"JOINED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CHAT_MESSAGES
--------------------------------------------------------

  CREATE TABLE "MOYEODDUGI"."CHAT_MESSAGES" 
   (	"MESSAGE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ROOM_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"CONTENT" VARCHAR2(2000 BYTE), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CHAT_ROOMS
--------------------------------------------------------

  CREATE TABLE "MOYEODDUGI"."CHAT_ROOMS" 
   (	"ROOM_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"POST_ID" NUMBER, 
	"ROOM_NAME" VARCHAR2(200 BYTE), 
	"MAX_MEMBERS" NUMBER, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMMENTS
--------------------------------------------------------

  CREATE TABLE "MOYEODDUGI"."COMMENTS" 
   (	"COMMENT_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TARGET_TYPE" VARCHAR2(10 BYTE), 
	"TARGET_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"CONTENT" VARCHAR2(1000 BYTE), 
	"PARENT_ID" NUMBER, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"REPLY_TO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FOLLOWS
--------------------------------------------------------

  CREATE TABLE "MOYEODDUGI"."FOLLOWS" 
   (	"FOLLOW_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"FOLLOWER_ID" NUMBER, 
	"FOLLOWING_ID" NUMBER, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LIKES
--------------------------------------------------------

  CREATE TABLE "MOYEODDUGI"."LIKES" 
   (	"LIKE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USER_ID" NUMBER, 
	"TARGET_TYPE" VARCHAR2(10 BYTE), 
	"TARGET_ID" NUMBER, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NOTIFICATIONS
--------------------------------------------------------

  CREATE TABLE "MOYEODDUGI"."NOTIFICATIONS" 
   (	"NOTI_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"RECEIVER_ID" NUMBER, 
	"SENDER_ID" NUMBER, 
	"NOTI_TYPE" VARCHAR2(20 BYTE), 
	"TARGET_TYPE" VARCHAR2(10 BYTE), 
	"TARGET_ID" NUMBER, 
	"MESSAGE" VARCHAR2(500 BYTE), 
	"IS_READ" CHAR(1 BYTE) DEFAULT 'N', 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PATTERNS
--------------------------------------------------------

  CREATE TABLE "MOYEODDUGI"."PATTERNS" 
   (	"PATTERN_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USER_ID" NUMBER, 
	"TITLE" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"NEEDLE_TYPE" VARCHAR2(10 BYTE), 
	"DIFFICULTY" VARCHAR2(10 BYTE), 
	"YARN_TYPE" VARCHAR2(100 BYTE), 
	"NEEDLE_SIZE" VARCHAR2(50 BYTE), 
	"FINISHED_SIZE" VARCHAR2(100 BYTE), 
	"WORK_TIME" VARCHAR2(50 BYTE), 
	"THUMBNAIL_IMG" VARCHAR2(500 BYTE), 
	"VIEW_COUNT" NUMBER DEFAULT 0, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"CATEGORY" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PATTERN_IMAGES
--------------------------------------------------------

  CREATE TABLE "MOYEODDUGI"."PATTERN_IMAGES" 
   (	"IMAGE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PATTERN_ID" NUMBER, 
	"IMAGE_URL" VARCHAR2(500 BYTE), 
	"SORT_ORDER" NUMBER DEFAULT 0, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PATTERN_TAGS
--------------------------------------------------------

  CREATE TABLE "MOYEODDUGI"."PATTERN_TAGS" 
   (	"TAG_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PATTERN_ID" NUMBER, 
	"TAG_NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PLACES
--------------------------------------------------------

  CREATE TABLE "MOYEODDUGI"."PLACES" 
   (	"PLACE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USER_ID" NUMBER, 
	"PLACE_NAME" VARCHAR2(100 BYTE), 
	"PLACE_TYPE" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(300 BYTE), 
	"LATITUDE" NUMBER(10,7), 
	"LONGITUDE" NUMBER(10,7), 
	"ALLOW_STATUS" VARCHAR2(10 BYTE), 
	"HAS_WIDE_TABLE" CHAR(1 BYTE) DEFAULT 'N', 
	"HAS_OUTLET" CHAR(1 BYTE) DEFAULT 'N', 
	"IS_QUIET" CHAR(1 BYTE) DEFAULT 'N', 
	"NO_TIME_LIMIT" CHAR(1 BYTE) DEFAULT 'N', 
	"HAS_MANY_SEATS" CHAR(1 BYTE) DEFAULT 'N', 
	"NO_MIN_ORDER" CHAR(1 BYTE) DEFAULT 'N', 
	"HAS_PARKING" CHAR(1 BYTE) DEFAULT 'N', 
	"IS_24HOURS" CHAR(1 BYTE) DEFAULT 'N', 
	"HAS_OUTDOOR" CHAR(1 BYTE) DEFAULT 'N', 
	"PET_FRIENDLY" CHAR(1 BYTE) DEFAULT 'N', 
	"HAS_FOOD" CHAR(1 BYTE) DEFAULT 'N', 
	"HAS_RESTROOM" CHAR(1 BYTE) DEFAULT 'N', 
	"PLACE_IMG" VARCHAR2(500 BYTE), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PLACE_REVIEWS
--------------------------------------------------------

  CREATE TABLE "MOYEODDUGI"."PLACE_REVIEWS" 
   (	"REVIEW_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PLACE_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"CONTENT" VARCHAR2(500 BYTE), 
	"ALLOW_STATUS" VARCHAR2(20 BYTE), 
	"REVIEW_IMG" VARCHAR2(500 BYTE), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table POSTS
--------------------------------------------------------

  CREATE TABLE "MOYEODDUGI"."POSTS" 
   (	"POST_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USER_ID" NUMBER, 
	"BOARD_TYPE" VARCHAR2(10 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" VARCHAR2(4000 BYTE), 
	"VIEW_COUNT" NUMBER DEFAULT 0, 
	"GATHER_STATUS" VARCHAR2(10 BYTE), 
	"GATHER_COUNT" NUMBER, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table POST_IMAGES
--------------------------------------------------------

  CREATE TABLE "MOYEODDUGI"."POST_IMAGES" 
   (	"IMAGE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"POST_ID" NUMBER, 
	"IMAGE_URL" VARCHAR2(500 BYTE), 
	"IS_THUMBNAIL" CHAR(1 BYTE) DEFAULT 'N', 
	"SORT_ORDER" NUMBER DEFAULT 0, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SCRAPS
--------------------------------------------------------

  CREATE TABLE "MOYEODDUGI"."SCRAPS" 
   (	"SCRAP_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USER_ID" NUMBER, 
	"TARGET_TYPE" VARCHAR2(10 BYTE), 
	"TARGET_ID" NUMBER, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "MOYEODDUGI"."USERS" 
   (	"USER_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE), 
	"SOCIAL_PROVIDER" VARCHAR2(20 BYTE), 
	"SOCIAL_ID" VARCHAR2(100 BYTE), 
	"NICKNAME" VARCHAR2(50 BYTE), 
	"PROFILE_IMG" VARCHAR2(500 BYTE), 
	"BIO" VARCHAR2(200 BYTE), 
	"USER_ROLE" VARCHAR2(10 BYTE) DEFAULT 'USER', 
	"STATUS" VARCHAR2(10 BYTE) DEFAULT 'ACTIVE', 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"USER_NAME" VARCHAR2(50 BYTE), 
	"BIRTH_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into MOYEODDUGI.CHAT_MEMBERS
SET DEFINE OFF;
REM INSERTING into MOYEODDUGI.CHAT_MESSAGES
SET DEFINE OFF;
REM INSERTING into MOYEODDUGI.CHAT_ROOMS
SET DEFINE OFF;
REM INSERTING into MOYEODDUGI.COMMENTS
SET DEFINE OFF;
Insert into MOYEODDUGI.COMMENTS (COMMENT_ID,TARGET_TYPE,TARGET_ID,USER_ID,CONTENT,PARENT_ID,CREATED_AT,UPDATED_AT,REPLY_TO) values (1,'POST',13,1,'가입인사합니다 ㅋㅋ',null,to_timestamp('26/06/01 10:32:03.053000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 12:04:42.088000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into MOYEODDUGI.COMMENTS (COMMENT_ID,TARGET_TYPE,TARGET_ID,USER_ID,CONTENT,PARENT_ID,CREATED_AT,UPDATED_AT,REPLY_TO) values (20,'POST',13,1,'ㅋㅋㅋㅋㅋ',1,to_timestamp('26/06/01 12:21:38.512000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 12:21:38.512000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into MOYEODDUGI.COMMENTS (COMMENT_ID,TARGET_TYPE,TARGET_ID,USER_ID,CONTENT,PARENT_ID,CREATED_AT,UPDATED_AT,REPLY_TO) values (3,'POST',13,21,'저 있어요 ㅎㅎ',1,to_timestamp('26/06/01 10:32:55.605000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 10:32:55.605000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into MOYEODDUGI.COMMENTS (COMMENT_ID,TARGET_TYPE,TARGET_ID,USER_ID,CONTENT,PARENT_ID,CREATED_AT,UPDATED_AT,REPLY_TO) values (4,'POST',13,21,'댓글 입니다.',null,to_timestamp('26/06/01 10:38:19.063000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 10:38:19.063000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into MOYEODDUGI.COMMENTS (COMMENT_ID,TARGET_TYPE,TARGET_ID,USER_ID,CONTENT,PARENT_ID,CREATED_AT,UPDATED_AT,REPLY_TO) values (5,'POST',13,21,'어디에 달리는거죠',1,to_timestamp('26/06/01 10:42:52.839000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 10:42:52.839000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into MOYEODDUGI.COMMENTS (COMMENT_ID,TARGET_TYPE,TARGET_ID,USER_ID,CONTENT,PARENT_ID,CREATED_AT,UPDATED_AT,REPLY_TO) values (21,'POST',13,1,'@뜨개중독 ㅋㅋㅋㅋ',1,to_timestamp('26/06/01 12:21:42.351000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 12:21:42.351000000','RR/MM/DD HH24:MI:SSXFF'),20);
Insert into MOYEODDUGI.COMMENTS (COMMENT_ID,TARGET_TYPE,TARGET_ID,USER_ID,CONTENT,PARENT_ID,CREATED_AT,UPDATED_AT,REPLY_TO) values (7,'POST',13,1,'하루의하루에게 답글',1,to_timestamp('26/06/01 11:19:17.657000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 11:19:17.657000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into MOYEODDUGI.COMMENTS (COMMENT_ID,TARGET_TYPE,TARGET_ID,USER_ID,CONTENT,PARENT_ID,CREATED_AT,UPDATED_AT,REPLY_TO) values (22,'POST',13,1,'@뜨개중독 ㅎㅎㅎ',1,to_timestamp('26/06/01 12:21:50.416000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 12:21:50.416000000','RR/MM/DD HH24:MI:SSXFF'),21);
Insert into MOYEODDUGI.COMMENTS (COMMENT_ID,TARGET_TYPE,TARGET_ID,USER_ID,CONTENT,PARENT_ID,CREATED_AT,UPDATED_AT,REPLY_TO) values (23,'POST',13,1,'@뜨개중독 ㅎㅎㅎㅎㅎㅎ',1,to_timestamp('26/06/01 12:22:00.184000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 12:22:00.184000000','RR/MM/DD HH24:MI:SSXFF'),21);
Insert into MOYEODDUGI.COMMENTS (COMMENT_ID,TARGET_TYPE,TARGET_ID,USER_ID,CONTENT,PARENT_ID,CREATED_AT,UPDATED_AT,REPLY_TO) values (10,'POST',12,1,'유튜브 추천합니다.',null,to_timestamp('26/06/01 11:45:41.919000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 11:45:41.919000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into MOYEODDUGI.COMMENTS (COMMENT_ID,TARGET_TYPE,TARGET_ID,USER_ID,CONTENT,PARENT_ID,CREATED_AT,UPDATED_AT,REPLY_TO) values (11,'POST',12,1,'링크는 마이페이지에 있어요 ㅎ',10,to_timestamp('26/06/01 11:45:50.955000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 11:45:50.955000000','RR/MM/DD HH24:MI:SSXFF'),null);
REM INSERTING into MOYEODDUGI.FOLLOWS
SET DEFINE OFF;
REM INSERTING into MOYEODDUGI.LIKES
SET DEFINE OFF;
Insert into MOYEODDUGI.LIKES (LIKE_ID,USER_ID,TARGET_TYPE,TARGET_ID,CREATED_AT) values (4,1,'POST',13,to_timestamp('26/06/01 12:43:44.008000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.LIKES (LIKE_ID,USER_ID,TARGET_TYPE,TARGET_ID,CREATED_AT) values (5,1,'POST',12,to_timestamp('26/06/01 12:43:44.991000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.LIKES (LIKE_ID,USER_ID,TARGET_TYPE,TARGET_ID,CREATED_AT) values (6,21,'POST',13,to_timestamp('26/06/01 12:44:16.768000000','RR/MM/DD HH24:MI:SSXFF'));
REM INSERTING into MOYEODDUGI.NOTIFICATIONS
SET DEFINE OFF;
REM INSERTING into MOYEODDUGI.PATTERNS
SET DEFINE OFF;
Insert into MOYEODDUGI.PATTERNS (PATTERN_ID,USER_ID,TITLE,DESCRIPTION,NEEDLE_TYPE,DIFFICULTY,YARN_TYPE,NEEDLE_SIZE,FINISHED_SIZE,WORK_TIME,THUMBNAIL_IMG,VIEW_COUNT,CREATED_AT,UPDATED_AT,CATEGORY) values (1,1,'귀여운 곰돌이 인형 만들기 바지 포함','대바늘로 만들 수 있는 곰인형입니다. ㅎㅎ
눈알 같은 부자재 구입처는 별도로 기입해두겠습니다.','코바늘','중급','곰돌이 실','6호','20cm','6시간',null,0,to_timestamp('26/06/01 17:20:35.553000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 17:20:35.553000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into MOYEODDUGI.PATTERNS (PATTERN_ID,USER_ID,TITLE,DESCRIPTION,NEEDLE_TYPE,DIFFICULTY,YARN_TYPE,NEEDLE_SIZE,FINISHED_SIZE,WORK_TIME,THUMBNAIL_IMG,VIEW_COUNT,CREATED_AT,UPDATED_AT,CATEGORY) values (2,1,'여름 린넨 가방 만들기','여름에 들고 다니기 좋은 린넨 소재 가방입니다.','코바늘','입문','프라다실','5호','40cm','4시간',null,0,to_timestamp('26/06/01 17:28:26.849000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 17:28:26.849000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into MOYEODDUGI.PATTERNS (PATTERN_ID,USER_ID,TITLE,DESCRIPTION,NEEDLE_TYPE,DIFFICULTY,YARN_TYPE,NEEDLE_SIZE,FINISHED_SIZE,WORK_TIME,THUMBNAIL_IMG,VIEW_COUNT,CREATED_AT,UPDATED_AT,CATEGORY) values (6,1,'아기 토끼 인형 만들기','아기들이 좋아해요','대바늘','중급','오가닉 실','6호','귀포함 50cm','5시간',null,0,to_timestamp('26/06/01 17:39:44.176000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 17:39:44.176000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into MOYEODDUGI.PATTERNS (PATTERN_ID,USER_ID,TITLE,DESCRIPTION,NEEDLE_TYPE,DIFFICULTY,YARN_TYPE,NEEDLE_SIZE,FINISHED_SIZE,WORK_TIME,THUMBNAIL_IMG,VIEW_COUNT,CREATED_AT,UPDATED_AT,CATEGORY) values (7,1,'데이지 책갈피','금방 뜨고 선물용으로 좋습니다.','코바늘','입문','다이소실','5호','15cm','10분',null,0,to_timestamp('26/06/01 17:43:37.197000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 17:43:37.197000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into MOYEODDUGI.PATTERNS (PATTERN_ID,USER_ID,TITLE,DESCRIPTION,NEEDLE_TYPE,DIFFICULTY,YARN_TYPE,NEEDLE_SIZE,FINISHED_SIZE,WORK_TIME,THUMBNAIL_IMG,VIEW_COUNT,CREATED_AT,UPDATED_AT,CATEGORY) values (8,1,'체커 모자','패셔너블한 체커 모자입니다. 기본만 알면 쉽게 뜰 수 있어요.','코바늘','초급','로미오실','5-6호','30cm','3시간','/uploads/patterns/pattern_1780304192312.jpg',0,to_timestamp('26/06/01 17:56:32.329000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 17:56:32.329000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into MOYEODDUGI.PATTERNS (PATTERN_ID,USER_ID,TITLE,DESCRIPTION,NEEDLE_TYPE,DIFFICULTY,YARN_TYPE,NEEDLE_SIZE,FINISHED_SIZE,WORK_TIME,THUMBNAIL_IMG,VIEW_COUNT,CREATED_AT,UPDATED_AT,CATEGORY) values (9,1,'테스트','테스트','코바늘','초급','다이소실','5호','30cm','4시간','/uploads/patterns/pattern_1780305084762.jpg',0,to_timestamp('26/06/01 18:11:24.772000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 18:11:24.772000000','RR/MM/DD HH24:MI:SSXFF'),null);
REM INSERTING into MOYEODDUGI.PATTERN_IMAGES
SET DEFINE OFF;
REM INSERTING into MOYEODDUGI.PATTERN_TAGS
SET DEFINE OFF;
Insert into MOYEODDUGI.PATTERN_TAGS (TAG_ID,PATTERN_ID,TAG_NAME) values (1,6,'인형');
Insert into MOYEODDUGI.PATTERN_TAGS (TAG_ID,PATTERN_ID,TAG_NAME) values (2,7,'소품');
Insert into MOYEODDUGI.PATTERN_TAGS (TAG_ID,PATTERN_ID,TAG_NAME) values (3,7,'선물용');
Insert into MOYEODDUGI.PATTERN_TAGS (TAG_ID,PATTERN_ID,TAG_NAME) values (5,8,'"');
Insert into MOYEODDUGI.PATTERN_TAGS (TAG_ID,PATTERN_ID,TAG_NAME) values (6,8,'모');
Insert into MOYEODDUGI.PATTERN_TAGS (TAG_ID,PATTERN_ID,TAG_NAME) values (7,8,'자');
Insert into MOYEODDUGI.PATTERN_TAGS (TAG_ID,PATTERN_ID,TAG_NAME) values (8,8,'"');
Insert into MOYEODDUGI.PATTERN_TAGS (TAG_ID,PATTERN_ID,TAG_NAME) values (9,8,',');
Insert into MOYEODDUGI.PATTERN_TAGS (TAG_ID,PATTERN_ID,TAG_NAME) values (10,8,'"');
Insert into MOYEODDUGI.PATTERN_TAGS (TAG_ID,PATTERN_ID,TAG_NAME) values (11,8,'의');
Insert into MOYEODDUGI.PATTERN_TAGS (TAG_ID,PATTERN_ID,TAG_NAME) values (12,8,'류');
Insert into MOYEODDUGI.PATTERN_TAGS (TAG_ID,PATTERN_ID,TAG_NAME) values (13,8,'"');
Insert into MOYEODDUGI.PATTERN_TAGS (TAG_ID,PATTERN_ID,TAG_NAME) values (14,8,']');
Insert into MOYEODDUGI.PATTERN_TAGS (TAG_ID,PATTERN_ID,TAG_NAME) values (15,9,'가방');
Insert into MOYEODDUGI.PATTERN_TAGS (TAG_ID,PATTERN_ID,TAG_NAME) values (16,9,'소품');
Insert into MOYEODDUGI.PATTERN_TAGS (TAG_ID,PATTERN_ID,TAG_NAME) values (17,9,'의류');
REM INSERTING into MOYEODDUGI.PLACES
SET DEFINE OFF;
Insert into MOYEODDUGI.PLACES (PLACE_ID,USER_ID,PLACE_NAME,PLACE_TYPE,ADDRESS,LATITUDE,LONGITUDE,ALLOW_STATUS,HAS_WIDE_TABLE,HAS_OUTLET,IS_QUIET,NO_TIME_LIMIT,HAS_MANY_SEATS,NO_MIN_ORDER,HAS_PARKING,IS_24HOURS,HAS_OUTDOOR,PET_FRIENDLY,HAS_FOOD,HAS_RESTROOM,PLACE_IMG,CREATED_AT,UPDATED_AT) values (1,1,'스타벅스 부평점','카페','인천광역시 부평구 부평대로 1',37.4899,126.7235,'허용','Y','Y','N','N','N','N','N','N','N','N','N','N',null,to_timestamp('26/06/01 15:06:00.102000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 15:06:00.102000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACES (PLACE_ID,USER_ID,PLACE_NAME,PLACE_TYPE,ADDRESS,LATITUDE,LONGITUDE,ALLOW_STATUS,HAS_WIDE_TABLE,HAS_OUTLET,IS_QUIET,NO_TIME_LIMIT,HAS_MANY_SEATS,NO_MIN_ORDER,HAS_PARKING,IS_24HOURS,HAS_OUTDOOR,PET_FRIENDLY,HAS_FOOD,HAS_RESTROOM,PLACE_IMG,CREATED_AT,UPDATED_AT) values (2,1,'이디야 부평역점','카페','인천광역시 부평구 부평로 10',37.4877,126.7219,'금지','N','N','N','N','N','N','N','N','N','N','N','N',null,to_timestamp('26/06/01 15:06:00.109000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 15:06:00.109000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACES (PLACE_ID,USER_ID,PLACE_NAME,PLACE_TYPE,ADDRESS,LATITUDE,LONGITUDE,ALLOW_STATUS,HAS_WIDE_TABLE,HAS_OUTLET,IS_QUIET,NO_TIME_LIMIT,HAS_MANY_SEATS,NO_MIN_ORDER,HAS_PARKING,IS_24HOURS,HAS_OUTDOOR,PET_FRIENDLY,HAS_FOOD,HAS_RESTROOM,PLACE_IMG,CREATED_AT,UPDATED_AT) values (3,1,'스타벅스 홍대입구점','카페','서울특별시 마포구 양화로 160',37.5563,126.9226,'허용','Y','Y','N','N','Y','N','N','N','N','N','N','Y',null,to_timestamp('26/06/01 15:24:38.458000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 15:24:38.458000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACES (PLACE_ID,USER_ID,PLACE_NAME,PLACE_TYPE,ADDRESS,LATITUDE,LONGITUDE,ALLOW_STATUS,HAS_WIDE_TABLE,HAS_OUTLET,IS_QUIET,NO_TIME_LIMIT,HAS_MANY_SEATS,NO_MIN_ORDER,HAS_PARKING,IS_24HOURS,HAS_OUTDOOR,PET_FRIENDLY,HAS_FOOD,HAS_RESTROOM,PLACE_IMG,CREATED_AT,UPDATED_AT) values (4,1,'이디야 강남점','카페','서울특별시 강남구 강남대로 396',37.4979,127.0276,'금지','N','N','N','N','N','N','N','N','N','N','N','Y',null,to_timestamp('26/06/01 15:24:38.465000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 15:24:38.465000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACES (PLACE_ID,USER_ID,PLACE_NAME,PLACE_TYPE,ADDRESS,LATITUDE,LONGITUDE,ALLOW_STATUS,HAS_WIDE_TABLE,HAS_OUTLET,IS_QUIET,NO_TIME_LIMIT,HAS_MANY_SEATS,NO_MIN_ORDER,HAS_PARKING,IS_24HOURS,HAS_OUTDOOR,PET_FRIENDLY,HAS_FOOD,HAS_RESTROOM,PLACE_IMG,CREATED_AT,UPDATED_AT) values (6,1,'할리스 건대점','카페','서울특별시 광진구 능동로 126',37.5403,127.07,'허용','N','Y','Y','Y','N','N','N','N','N','N','N','Y',null,to_timestamp('26/06/01 15:24:38.551000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 15:24:38.551000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACES (PLACE_ID,USER_ID,PLACE_NAME,PLACE_TYPE,ADDRESS,LATITUDE,LONGITUDE,ALLOW_STATUS,HAS_WIDE_TABLE,HAS_OUTLET,IS_QUIET,NO_TIME_LIMIT,HAS_MANY_SEATS,NO_MIN_ORDER,HAS_PARKING,IS_24HOURS,HAS_OUTDOOR,PET_FRIENDLY,HAS_FOOD,HAS_RESTROOM,PLACE_IMG,CREATED_AT,UPDATED_AT) values (7,1,'메가커피 종로점','카페','서울특별시 종로구 종로 51',37.5706,126.9897,'금지','N','N','N','N','Y','N','N','N','N','N','N','Y',null,to_timestamp('26/06/01 15:24:38.555000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 15:24:38.555000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACES (PLACE_ID,USER_ID,PLACE_NAME,PLACE_TYPE,ADDRESS,LATITUDE,LONGITUDE,ALLOW_STATUS,HAS_WIDE_TABLE,HAS_OUTLET,IS_QUIET,NO_TIME_LIMIT,HAS_MANY_SEATS,NO_MIN_ORDER,HAS_PARKING,IS_24HOURS,HAS_OUTDOOR,PET_FRIENDLY,HAS_FOOD,HAS_RESTROOM,PLACE_IMG,CREATED_AT,UPDATED_AT) values (8,1,'카페베네 합정점','카페','서울특별시 마포구 합정동 358',37.5495,126.9143,'허용','Y','Y','Y','Y','Y','N','N','N','N','N','N','Y',null,to_timestamp('26/06/01 15:24:38.560000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 15:24:38.560000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACES (PLACE_ID,USER_ID,PLACE_NAME,PLACE_TYPE,ADDRESS,LATITUDE,LONGITUDE,ALLOW_STATUS,HAS_WIDE_TABLE,HAS_OUTLET,IS_QUIET,NO_TIME_LIMIT,HAS_MANY_SEATS,NO_MIN_ORDER,HAS_PARKING,IS_24HOURS,HAS_OUTDOOR,PET_FRIENDLY,HAS_FOOD,HAS_RESTROOM,PLACE_IMG,CREATED_AT,UPDATED_AT) values (10,1,'폴바셋 서울숲점','카페','서울특별시 성동구 왕십리로 83',37.5445,127.0441,'허용','Y','Y','Y','N','N','N','N','N','N','Y','N','Y',null,to_timestamp('26/06/01 15:24:38.585000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 15:24:38.585000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACES (PLACE_ID,USER_ID,PLACE_NAME,PLACE_TYPE,ADDRESS,LATITUDE,LONGITUDE,ALLOW_STATUS,HAS_WIDE_TABLE,HAS_OUTLET,IS_QUIET,NO_TIME_LIMIT,HAS_MANY_SEATS,NO_MIN_ORDER,HAS_PARKING,IS_24HOURS,HAS_OUTDOOR,PET_FRIENDLY,HAS_FOOD,HAS_RESTROOM,PLACE_IMG,CREATED_AT,UPDATED_AT) values (11,1,'스타벅스 부평점','카페','인천광역시 부평구 부평대로 1',37.4899,126.7235,'허용','Y','Y','N','N','N','N','N','N','N','N','N','Y',null,to_timestamp('26/06/01 15:24:38.592000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 15:24:38.592000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACES (PLACE_ID,USER_ID,PLACE_NAME,PLACE_TYPE,ADDRESS,LATITUDE,LONGITUDE,ALLOW_STATUS,HAS_WIDE_TABLE,HAS_OUTLET,IS_QUIET,NO_TIME_LIMIT,HAS_MANY_SEATS,NO_MIN_ORDER,HAS_PARKING,IS_24HOURS,HAS_OUTDOOR,PET_FRIENDLY,HAS_FOOD,HAS_RESTROOM,PLACE_IMG,CREATED_AT,UPDATED_AT) values (12,1,'이디야 인천터미널점','카페','인천광역시 남동구 인주대로 581',37.4473,126.7054,'금지','N','N','N','N','Y','N','N','N','N','N','N','Y',null,to_timestamp('26/06/01 15:24:38.598000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 15:24:38.598000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACES (PLACE_ID,USER_ID,PLACE_NAME,PLACE_TYPE,ADDRESS,LATITUDE,LONGITUDE,ALLOW_STATUS,HAS_WIDE_TABLE,HAS_OUTLET,IS_QUIET,NO_TIME_LIMIT,HAS_MANY_SEATS,NO_MIN_ORDER,HAS_PARKING,IS_24HOURS,HAS_OUTDOOR,PET_FRIENDLY,HAS_FOOD,HAS_RESTROOM,PLACE_IMG,CREATED_AT,UPDATED_AT) values (13,1,'카페 달달 송도점','카페','인천광역시 연수구 송도동 24-5',37.383,126.6564,'허용','Y','Y','Y','Y','Y','N','N','N','N','N','N','Y',null,to_timestamp('26/06/01 15:24:38.604000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 15:24:38.604000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACES (PLACE_ID,USER_ID,PLACE_NAME,PLACE_TYPE,ADDRESS,LATITUDE,LONGITUDE,ALLOW_STATUS,HAS_WIDE_TABLE,HAS_OUTLET,IS_QUIET,NO_TIME_LIMIT,HAS_MANY_SEATS,NO_MIN_ORDER,HAS_PARKING,IS_24HOURS,HAS_OUTDOOR,PET_FRIENDLY,HAS_FOOD,HAS_RESTROOM,PLACE_IMG,CREATED_AT,UPDATED_AT) values (15,1,'북카페 책마을 강화점','도서관','인천광역시 강화군 강화읍 중앙로 10',37.7478,126.4878,'허용','Y','N','Y','Y','Y','N','N','N','N','N','N','Y',null,to_timestamp('26/06/01 15:24:38.629000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 15:24:38.629000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACES (PLACE_ID,USER_ID,PLACE_NAME,PLACE_TYPE,ADDRESS,LATITUDE,LONGITUDE,ALLOW_STATUS,HAS_WIDE_TABLE,HAS_OUTLET,IS_QUIET,NO_TIME_LIMIT,HAS_MANY_SEATS,NO_MIN_ORDER,HAS_PARKING,IS_24HOURS,HAS_OUTDOOR,PET_FRIENDLY,HAS_FOOD,HAS_RESTROOM,PLACE_IMG,CREATED_AT,UPDATED_AT) values (16,1,'메가커피 계양점','카페','인천광역시 계양구 계산로 10',37.5374,126.7382,'금지','N','N','N','N','Y','N','N','N','N','N','N','N',null,to_timestamp('26/06/01 15:24:38.634000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 15:24:38.634000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACES (PLACE_ID,USER_ID,PLACE_NAME,PLACE_TYPE,ADDRESS,LATITUDE,LONGITUDE,ALLOW_STATUS,HAS_WIDE_TABLE,HAS_OUTLET,IS_QUIET,NO_TIME_LIMIT,HAS_MANY_SEATS,NO_MIN_ORDER,HAS_PARKING,IS_24HOURS,HAS_OUTDOOR,PET_FRIENDLY,HAS_FOOD,HAS_RESTROOM,PLACE_IMG,CREATED_AT,UPDATED_AT) values (17,1,'스타벅스 수원역점','카페','경기도 수원시 팔달구 덕영대로 924',37.2653,127.0005,'허용','Y','Y','N','N','Y','N','N','N','N','N','N','Y',null,to_timestamp('26/06/01 15:24:38.648000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 15:24:38.648000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACES (PLACE_ID,USER_ID,PLACE_NAME,PLACE_TYPE,ADDRESS,LATITUDE,LONGITUDE,ALLOW_STATUS,HAS_WIDE_TABLE,HAS_OUTLET,IS_QUIET,NO_TIME_LIMIT,HAS_MANY_SEATS,NO_MIN_ORDER,HAS_PARKING,IS_24HOURS,HAS_OUTDOOR,PET_FRIENDLY,HAS_FOOD,HAS_RESTROOM,PLACE_IMG,CREATED_AT,UPDATED_AT) values (18,1,'이디야 성남판교점','카페','경기도 성남시 분당구 판교역로 146',37.3948,127.1112,'금지','N','N','N','N','N','N','N','N','N','N','N','Y',null,to_timestamp('26/06/01 15:24:38.653000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 15:24:38.653000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACES (PLACE_ID,USER_ID,PLACE_NAME,PLACE_TYPE,ADDRESS,LATITUDE,LONGITUDE,ALLOW_STATUS,HAS_WIDE_TABLE,HAS_OUTLET,IS_QUIET,NO_TIME_LIMIT,HAS_MANY_SEATS,NO_MIN_ORDER,HAS_PARKING,IS_24HOURS,HAS_OUTDOOR,PET_FRIENDLY,HAS_FOOD,HAS_RESTROOM,PLACE_IMG,CREATED_AT,UPDATED_AT) values (19,1,'카페 온더테이블 용인점','카페','경기도 용인시 기흥구 동백죽전대로 16',37.2681,127.119,'허용','Y','Y','Y','Y','Y','N','N','N','N','Y','N','Y',null,to_timestamp('26/06/01 15:24:38.658000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 15:24:38.658000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACES (PLACE_ID,USER_ID,PLACE_NAME,PLACE_TYPE,ADDRESS,LATITUDE,LONGITUDE,ALLOW_STATUS,HAS_WIDE_TABLE,HAS_OUTLET,IS_QUIET,NO_TIME_LIMIT,HAS_MANY_SEATS,NO_MIN_ORDER,HAS_PARKING,IS_24HOURS,HAS_OUTDOOR,PET_FRIENDLY,HAS_FOOD,HAS_RESTROOM,PLACE_IMG,CREATED_AT,UPDATED_AT) values (21,1,'할리스 의정부점','카페','경기도 의정부시 의정부동 산10-1',37.7381,127.0472,'허용','Y','N','Y','Y','Y','N','N','N','N','N','N','Y',null,to_timestamp('26/06/01 15:24:38.685000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 15:24:38.685000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACES (PLACE_ID,USER_ID,PLACE_NAME,PLACE_TYPE,ADDRESS,LATITUDE,LONGITUDE,ALLOW_STATUS,HAS_WIDE_TABLE,HAS_OUTLET,IS_QUIET,NO_TIME_LIMIT,HAS_MANY_SEATS,NO_MIN_ORDER,HAS_PARKING,IS_24HOURS,HAS_OUTDOOR,PET_FRIENDLY,HAS_FOOD,HAS_RESTROOM,PLACE_IMG,CREATED_AT,UPDATED_AT) values (22,1,'빽다방 안양점','카페','경기도 안양시 만안구 안양로 10',37.3943,126.9568,'금지','N','N','N','N','Y','N','N','N','N','N','N','Y',null,to_timestamp('26/06/01 15:24:38.691000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 15:24:38.691000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACES (PLACE_ID,USER_ID,PLACE_NAME,PLACE_TYPE,ADDRESS,LATITUDE,LONGITUDE,ALLOW_STATUS,HAS_WIDE_TABLE,HAS_OUTLET,IS_QUIET,NO_TIME_LIMIT,HAS_MANY_SEATS,NO_MIN_ORDER,HAS_PARKING,IS_24HOURS,HAS_OUTDOOR,PET_FRIENDLY,HAS_FOOD,HAS_RESTROOM,PLACE_IMG,CREATED_AT,UPDATED_AT) values (23,1,'카페 소담 광주점','카페','경기도 광주시 경안로 10',37.4296,127.2553,'허용','Y','Y','Y','Y','N','N','N','N','N','N','N','Y',null,to_timestamp('26/06/01 15:24:38.697000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 15:24:38.697000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACES (PLACE_ID,USER_ID,PLACE_NAME,PLACE_TYPE,ADDRESS,LATITUDE,LONGITUDE,ALLOW_STATUS,HAS_WIDE_TABLE,HAS_OUTLET,IS_QUIET,NO_TIME_LIMIT,HAS_MANY_SEATS,NO_MIN_ORDER,HAS_PARKING,IS_24HOURS,HAS_OUTDOOR,PET_FRIENDLY,HAS_FOOD,HAS_RESTROOM,PLACE_IMG,CREATED_AT,UPDATED_AT) values (24,1,'구월 로데오 파스쿠찌','카페','인천 남동구 구월동 1463-2',37.4448541,126.7014931,'허용','Y','Y','N','N','Y','N','N','N','N','N','N','Y',null,to_timestamp('26/06/01 16:15:15.555000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 16:15:15.555000000','RR/MM/DD HH24:MI:SSXFF'));
REM INSERTING into MOYEODDUGI.PLACE_REVIEWS
SET DEFINE OFF;
Insert into MOYEODDUGI.PLACE_REVIEWS (REVIEW_ID,PLACE_ID,USER_ID,CONTENT,ALLOW_STATUS,REVIEW_IMG,CREATED_AT,UPDATED_AT) values (13,24,1,'테이블도 엄청 많고 3층이라서 좋습니다. ㅎㅎ','허용',null,to_timestamp('26/06/01 16:54:29.811000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 16:54:29.811000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACE_REVIEWS (REVIEW_ID,PLACE_ID,USER_ID,CONTENT,ALLOW_STATUS,REVIEW_IMG,CREATED_AT,UPDATED_AT) values (19,24,1,'딱히 막지 않는거 같아요','모르겠어요',null,to_timestamp('26/06/01 16:57:23.269000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 16:57:23.269000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACE_REVIEWS (REVIEW_ID,PLACE_ID,USER_ID,CONTENT,ALLOW_STATUS,REVIEW_IMG,CREATED_AT,UPDATED_AT) values (11,24,1,'거의 매일 가고 있어요','허용',null,to_timestamp('26/06/01 16:50:30.212000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 16:50:30.212000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.PLACE_REVIEWS (REVIEW_ID,PLACE_ID,USER_ID,CONTENT,ALLOW_STATUS,REVIEW_IMG,CREATED_AT,UPDATED_AT) values (20,24,1,'저는 금지 당했습니다 ㅠㅠ','금지',null,to_timestamp('26/06/01 16:57:42.979000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 16:57:42.979000000','RR/MM/DD HH24:MI:SSXFF'));
REM INSERTING into MOYEODDUGI.POSTS
SET DEFINE OFF;
Insert into MOYEODDUGI.POSTS (POST_ID,USER_ID,BOARD_TYPE,TITLE,CONTENT,VIEW_COUNT,GATHER_STATUS,GATHER_COUNT,CREATED_AT,UPDATED_AT) values (1,1,'자유','첫 번째 자유 게시글','안녕하세요! 뜨개질 시작한 지 얼마 안 됐어요 😊',2,null,null,to_timestamp('26/05/30 14:04:08.375000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/05/30 14:34:25.956000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.POSTS (POST_ID,USER_ID,BOARD_TYPE,TITLE,CONTENT,VIEW_COUNT,GATHER_STATUS,GATHER_COUNT,CREATED_AT,UPDATED_AT) values (2,1,'질문','코바늘 기초 질문이요!','한길긴뜨기랑 긴뜨기 차이가 뭔가요?',0,null,null,to_timestamp('26/05/30 14:04:08.386000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/05/30 14:04:08.386000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.POSTS (POST_ID,USER_ID,BOARD_TYPE,TITLE,CONTENT,VIEW_COUNT,GATHER_STATUS,GATHER_COUNT,CREATED_AT,UPDATED_AT) values (7,1,'자유','오늘 카페에서 뜨개질 했어요!','부평 스타벅스에서 3시간 뜨개질 ㅎㅎ',0,null,null,to_timestamp('26/05/30 14:59:47.683000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/05/30 14:59:47.683000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.POSTS (POST_ID,USER_ID,BOARD_TYPE,TITLE,CONTENT,VIEW_COUNT,GATHER_STATUS,GATHER_COUNT,CREATED_AT,UPDATED_AT) values (11,1,'자유','첫 작품 완성했어요!!','드디어 곰돌이 인형 완성 ㅠㅠ 너무 뿌듯해요',0,null,null,to_timestamp('26/05/30 14:59:47.743000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/05/30 14:59:47.743000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.POSTS (POST_ID,USER_ID,BOARD_TYPE,TITLE,CONTENT,VIEW_COUNT,GATHER_STATUS,GATHER_COUNT,CREATED_AT,UPDATED_AT) values (12,1,'질문','실 엉킨거 푸는 팁 있나요?','뜨다가 실이 너무 엉켜서 힘드네요 ㅠㅠ',0,null,null,to_timestamp('26/05/30 14:59:47.747000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/05/30 14:59:47.747000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into MOYEODDUGI.POSTS (POST_ID,USER_ID,BOARD_TYPE,TITLE,CONTENT,VIEW_COUNT,GATHER_STATUS,GATHER_COUNT,CREATED_AT,UPDATED_AT) values (13,1,'자유','가입인사','가입했어요 ㅎ',0,null,null,to_timestamp('26/06/01 10:08:26.614000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 10:08:26.614000000','RR/MM/DD HH24:MI:SSXFF'));
REM INSERTING into MOYEODDUGI.POST_IMAGES
SET DEFINE OFF;
REM INSERTING into MOYEODDUGI.SCRAPS
SET DEFINE OFF;
REM INSERTING into MOYEODDUGI.USERS
SET DEFINE OFF;
Insert into MOYEODDUGI.USERS (USER_ID,EMAIL,PASSWORD,SOCIAL_PROVIDER,SOCIAL_ID,NICKNAME,PROFILE_IMG,BIO,USER_ROLE,STATUS,CREATED_AT,UPDATED_AT,USER_NAME,BIRTH_DATE) values (1,'test@test.com','$2b$10$8AuuQOHiXqBsllXUcagfgO40j6Xcz6KNQMQNY0R50x0PaABv/o2xu',null,null,'뜨개중독',null,null,'USER','ACTIVE',to_timestamp('26/05/29 15:12:57.899000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/05/29 15:12:57.899000000','RR/MM/DD HH24:MI:SSXFF'),'테스트',null);
Insert into MOYEODDUGI.USERS (USER_ID,EMAIL,PASSWORD,SOCIAL_PROVIDER,SOCIAL_ID,NICKNAME,PROFILE_IMG,BIO,USER_ROLE,STATUS,CREATED_AT,UPDATED_AT,USER_NAME,BIRTH_DATE) values (2,'wahaha@nate.com','$2b$10$3YO/j6dGDtDBOxJgK2om9ObbgzI6tFTKf9OicQ9zbUzRshqEZozze',null,null,'코뜨는치와와',null,null,'USER','ACTIVE',to_timestamp('26/05/29 16:10:38.748000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/05/29 16:10:38.748000000','RR/MM/DD HH24:MI:SSXFF'),'김하나',null);
Insert into MOYEODDUGI.USERS (USER_ID,EMAIL,PASSWORD,SOCIAL_PROVIDER,SOCIAL_ID,NICKNAME,PROFILE_IMG,BIO,USER_ROLE,STATUS,CREATED_AT,UPDATED_AT,USER_NAME,BIRTH_DATE) values (21,'hiru@naver.com','$2b$10$pgX9kPFMMAcCdbjmc/LW..V9aQjfLAduh697euz7XcmMo9LUKsMTW',null,null,'하루의하루',null,null,'USER','ACTIVE',to_timestamp('26/06/01 09:39:08.960000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('26/06/01 09:39:08.960000000','RR/MM/DD HH24:MI:SSXFF'),'이하루',null);
--------------------------------------------------------
--  DDL for Index UQ_CHAT_MEMBERS
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOYEODDUGI"."UQ_CHAT_MEMBERS" ON "MOYEODDUGI"."CHAT_MEMBERS" ("ROOM_ID", "USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_CHAT_ROOM_POST
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOYEODDUGI"."UQ_CHAT_ROOM_POST" ON "MOYEODDUGI"."CHAT_ROOMS" ("POST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_FOLLOWS
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOYEODDUGI"."UQ_FOLLOWS" ON "MOYEODDUGI"."FOLLOWS" ("FOLLOWER_ID", "FOLLOWING_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_LIKES
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOYEODDUGI"."UQ_LIKES" ON "MOYEODDUGI"."LIKES" ("USER_ID", "TARGET_TYPE", "TARGET_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_SCRAPS
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOYEODDUGI"."UQ_SCRAPS" ON "MOYEODDUGI"."SCRAPS" ("USER_ID", "TARGET_TYPE", "TARGET_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_USERS_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOYEODDUGI"."UQ_USERS_EMAIL" ON "MOYEODDUGI"."USERS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_USERS_NICKNAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOYEODDUGI"."UQ_USERS_NICKNAME" ON "MOYEODDUGI"."USERS" ("NICKNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRG_COMMENTS_UPDATED_AT
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "MOYEODDUGI"."TRG_COMMENTS_UPDATED_AT" 
    BEFORE UPDATE ON comments
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "MOYEODDUGI"."TRG_COMMENTS_UPDATED_AT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_PATTERNS_UPDATED_AT
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "MOYEODDUGI"."TRG_PATTERNS_UPDATED_AT" 
    BEFORE UPDATE ON patterns
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "MOYEODDUGI"."TRG_PATTERNS_UPDATED_AT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_PLACES_UPDATED_AT
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "MOYEODDUGI"."TRG_PLACES_UPDATED_AT" 
    BEFORE UPDATE ON places
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "MOYEODDUGI"."TRG_PLACES_UPDATED_AT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_PLACE_REVIEWS_UPDATED_AT
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "MOYEODDUGI"."TRG_PLACE_REVIEWS_UPDATED_AT" 
    BEFORE UPDATE ON place_reviews
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "MOYEODDUGI"."TRG_PLACE_REVIEWS_UPDATED_AT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_POSTS_UPDATED_AT
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "MOYEODDUGI"."TRG_POSTS_UPDATED_AT" 
    BEFORE UPDATE ON posts
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "MOYEODDUGI"."TRG_POSTS_UPDATED_AT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_USERS_UPDATED_AT
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "MOYEODDUGI"."TRG_USERS_UPDATED_AT" 
    BEFORE UPDATE ON users
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "MOYEODDUGI"."TRG_USERS_UPDATED_AT" ENABLE;
--------------------------------------------------------
--  Constraints for Table CHAT_ROOMS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."CHAT_ROOMS" MODIFY ("ROOM_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."CHAT_ROOMS" MODIFY ("POST_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."CHAT_ROOMS" MODIFY ("ROOM_NAME" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."CHAT_ROOMS" MODIFY ("MAX_MEMBERS" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."CHAT_ROOMS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."CHAT_ROOMS" ADD PRIMARY KEY ("ROOM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MOYEODDUGI"."CHAT_ROOMS" ADD CONSTRAINT "UQ_CHAT_ROOM_POST" UNIQUE ("POST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PATTERNS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."PATTERNS" MODIFY ("PATTERN_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PATTERNS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PATTERNS" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PATTERNS" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PATTERNS" MODIFY ("NEEDLE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PATTERNS" MODIFY ("DIFFICULTY" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PATTERNS" MODIFY ("VIEW_COUNT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PATTERNS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PATTERNS" MODIFY ("UPDATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PATTERNS" ADD CONSTRAINT "CHK_NEEDLE_TYPE" CHECK (needle_type IN ('코바늘', '대바늘')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."PATTERNS" ADD CONSTRAINT "CHK_DIFFICULTY" CHECK (difficulty IN ('입문', '초급', '중급', '고급')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."PATTERNS" ADD PRIMARY KEY ("PATTERN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MOYEODDUGI"."PATTERNS" ADD CONSTRAINT "CHK_PATTERN_CATEGORY" CHECK (category IN ('소품', '가방', '모자', '의류', '인형', '선물용', '기타')) ENABLE;
--------------------------------------------------------
--  Constraints for Table PATTERN_TAGS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."PATTERN_TAGS" MODIFY ("TAG_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PATTERN_TAGS" MODIFY ("PATTERN_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PATTERN_TAGS" MODIFY ("TAG_NAME" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PATTERN_TAGS" ADD PRIMARY KEY ("TAG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CHAT_MEMBERS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."CHAT_MEMBERS" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."CHAT_MEMBERS" MODIFY ("ROOM_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."CHAT_MEMBERS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."CHAT_MEMBERS" MODIFY ("IS_HOST" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."CHAT_MEMBERS" MODIFY ("JOINED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."CHAT_MEMBERS" ADD CONSTRAINT "CHK_IS_HOST" CHECK (is_host IN ('Y', 'N')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."CHAT_MEMBERS" ADD PRIMARY KEY ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MOYEODDUGI"."CHAT_MEMBERS" ADD CONSTRAINT "UQ_CHAT_MEMBERS" UNIQUE ("ROOM_ID", "USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."USERS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."USERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."USERS" MODIFY ("NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."USERS" MODIFY ("USER_ROLE" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."USERS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."USERS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."USERS" MODIFY ("UPDATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."USERS" ADD CONSTRAINT "CHK_USER_ROLE" CHECK (user_role IN ('USER', 'ADMIN')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."USERS" ADD CONSTRAINT "CHK_USER_STATUS" CHECK (status IN ('ACTIVE', 'INACTIVE', 'BANNED')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."USERS" ADD CONSTRAINT "CHK_SOCIAL_PROVIDER" CHECK (social_provider IN ('KAKAO', 'GOOGLE') 
                                          OR social_provider IS NULL) ENABLE;
  ALTER TABLE "MOYEODDUGI"."USERS" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MOYEODDUGI"."USERS" ADD CONSTRAINT "UQ_USERS_EMAIL" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MOYEODDUGI"."USERS" ADD CONSTRAINT "UQ_USERS_NICKNAME" UNIQUE ("NICKNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PLACES
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("PLACE_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("PLACE_NAME" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("PLACE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("LATITUDE" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("LONGITUDE" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("ALLOW_STATUS" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("HAS_WIDE_TABLE" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("HAS_OUTLET" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("IS_QUIET" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("NO_TIME_LIMIT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("HAS_MANY_SEATS" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("NO_MIN_ORDER" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("HAS_PARKING" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("IS_24HOURS" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("HAS_OUTDOOR" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("PET_FRIENDLY" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("HAS_FOOD" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("HAS_RESTROOM" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" MODIFY ("UPDATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACES" ADD CONSTRAINT "CHK_PLACE_TYPE" CHECK (place_type IN ('카페', '도서관', '공원', '기타')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."PLACES" ADD CONSTRAINT "CHK_ALLOW_STATUS" CHECK (allow_status IN ('허용', '묵인', '금지', '모르겠어요')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."PLACES" ADD CONSTRAINT "CHK_WIDE_TABLE" CHECK (has_wide_table IN ('Y', 'N')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."PLACES" ADD CONSTRAINT "CHK_OUTLET" CHECK (has_outlet IN ('Y', 'N')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."PLACES" ADD CONSTRAINT "CHK_QUIET" CHECK (is_quiet IN ('Y', 'N')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."PLACES" ADD CONSTRAINT "CHK_TIME_LIMIT" CHECK (no_time_limit IN ('Y', 'N')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."PLACES" ADD CONSTRAINT "CHK_MANY_SEATS" CHECK (has_many_seats IN ('Y', 'N')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."PLACES" ADD CONSTRAINT "CHK_MIN_ORDER" CHECK (no_min_order IN ('Y', 'N')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."PLACES" ADD CONSTRAINT "CHK_PARKING" CHECK (has_parking IN ('Y', 'N')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."PLACES" ADD CONSTRAINT "CHK_24HOURS" CHECK (is_24hours IN ('Y', 'N')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."PLACES" ADD CONSTRAINT "CHK_OUTDOOR" CHECK (has_outdoor IN ('Y', 'N')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."PLACES" ADD CONSTRAINT "CHK_PET" CHECK (pet_friendly IN ('Y', 'N')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."PLACES" ADD CONSTRAINT "CHK_FOOD" CHECK (has_food IN ('Y', 'N')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."PLACES" ADD CONSTRAINT "CHK_RESTROOM" CHECK (has_restroom IN ('Y', 'N')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."PLACES" ADD PRIMARY KEY ("PLACE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table POST_IMAGES
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."POST_IMAGES" MODIFY ("IMAGE_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."POST_IMAGES" MODIFY ("POST_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."POST_IMAGES" MODIFY ("IMAGE_URL" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."POST_IMAGES" MODIFY ("IS_THUMBNAIL" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."POST_IMAGES" MODIFY ("SORT_ORDER" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."POST_IMAGES" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."POST_IMAGES" ADD CONSTRAINT "CHK_THUMBNAIL" CHECK (is_thumbnail IN ('Y', 'N')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."POST_IMAGES" ADD PRIMARY KEY ("IMAGE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMMENTS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."COMMENTS" MODIFY ("COMMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."COMMENTS" MODIFY ("TARGET_TYPE" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."COMMENTS" MODIFY ("TARGET_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."COMMENTS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."COMMENTS" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."COMMENTS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."COMMENTS" MODIFY ("UPDATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."COMMENTS" ADD CONSTRAINT "CHK_COMMENT_TARGET" CHECK (target_type IN ('POST', 'PATTERN')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."COMMENTS" ADD PRIMARY KEY ("COMMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LIKES
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."LIKES" MODIFY ("LIKE_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."LIKES" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."LIKES" MODIFY ("TARGET_TYPE" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."LIKES" MODIFY ("TARGET_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."LIKES" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."LIKES" ADD CONSTRAINT "CHK_LIKES_TYPE" CHECK (target_type IN ('POST', 'PATTERN')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."LIKES" ADD PRIMARY KEY ("LIKE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MOYEODDUGI"."LIKES" ADD CONSTRAINT "UQ_LIKES" UNIQUE ("USER_ID", "TARGET_TYPE", "TARGET_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table POSTS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."POSTS" MODIFY ("POST_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."POSTS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."POSTS" MODIFY ("BOARD_TYPE" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."POSTS" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."POSTS" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."POSTS" MODIFY ("VIEW_COUNT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."POSTS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."POSTS" MODIFY ("UPDATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."POSTS" ADD CONSTRAINT "CHK_BOARD_TYPE" CHECK (board_type IN 
                                    ('자유', '질문', '모여떠요', '떠주세요', '떠드려요', '작품자랑')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."POSTS" ADD CONSTRAINT "CHK_GATHER_STATUS" CHECK (gather_status IN ('모집중', '마감') 
                                          OR gather_status IS NULL) ENABLE;
  ALTER TABLE "MOYEODDUGI"."POSTS" ADD PRIMARY KEY ("POST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SCRAPS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."SCRAPS" MODIFY ("SCRAP_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."SCRAPS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."SCRAPS" MODIFY ("TARGET_TYPE" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."SCRAPS" MODIFY ("TARGET_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."SCRAPS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."SCRAPS" ADD CONSTRAINT "CHK_SCRAPS_TYPE" CHECK (target_type IN ('PATTERN', 'POST')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."SCRAPS" ADD PRIMARY KEY ("SCRAP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MOYEODDUGI"."SCRAPS" ADD CONSTRAINT "UQ_SCRAPS" UNIQUE ("USER_ID", "TARGET_TYPE", "TARGET_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PATTERN_IMAGES
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."PATTERN_IMAGES" MODIFY ("IMAGE_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PATTERN_IMAGES" MODIFY ("PATTERN_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PATTERN_IMAGES" MODIFY ("IMAGE_URL" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PATTERN_IMAGES" MODIFY ("SORT_ORDER" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PATTERN_IMAGES" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PATTERN_IMAGES" ADD PRIMARY KEY ("IMAGE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PLACE_REVIEWS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."PLACE_REVIEWS" MODIFY ("REVIEW_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACE_REVIEWS" MODIFY ("PLACE_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACE_REVIEWS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACE_REVIEWS" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACE_REVIEWS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACE_REVIEWS" MODIFY ("UPDATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."PLACE_REVIEWS" ADD CONSTRAINT "CHK_REVIEW_ALLOW" CHECK (allow_status IN ('허용', '묵인', '금지', '모르겠어요')
                                          OR allow_status IS NULL) ENABLE;
  ALTER TABLE "MOYEODDUGI"."PLACE_REVIEWS" ADD PRIMARY KEY ("REVIEW_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FOLLOWS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."FOLLOWS" MODIFY ("FOLLOW_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."FOLLOWS" MODIFY ("FOLLOWER_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."FOLLOWS" MODIFY ("FOLLOWING_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."FOLLOWS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."FOLLOWS" ADD CONSTRAINT "CHK_FOLLOWS_SELF" CHECK (follower_id != following_id) ENABLE;
  ALTER TABLE "MOYEODDUGI"."FOLLOWS" ADD PRIMARY KEY ("FOLLOW_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MOYEODDUGI"."FOLLOWS" ADD CONSTRAINT "UQ_FOLLOWS" UNIQUE ("FOLLOWER_ID", "FOLLOWING_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CHAT_MESSAGES
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."CHAT_MESSAGES" MODIFY ("MESSAGE_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."CHAT_MESSAGES" MODIFY ("ROOM_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."CHAT_MESSAGES" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."CHAT_MESSAGES" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."CHAT_MESSAGES" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."CHAT_MESSAGES" ADD PRIMARY KEY ("MESSAGE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table NOTIFICATIONS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."NOTIFICATIONS" MODIFY ("NOTI_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."NOTIFICATIONS" MODIFY ("RECEIVER_ID" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."NOTIFICATIONS" MODIFY ("NOTI_TYPE" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."NOTIFICATIONS" MODIFY ("MESSAGE" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."NOTIFICATIONS" MODIFY ("IS_READ" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."NOTIFICATIONS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "MOYEODDUGI"."NOTIFICATIONS" ADD CONSTRAINT "CHK_NOTI_TYPE" CHECK (noti_type IN 
                                    ('NEW_PATTERN', 'COMMENT', 'LIKE', 'FOLLOW', 'GATHER')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."NOTIFICATIONS" ADD CONSTRAINT "CHK_NOTI_READ" CHECK (is_read IN ('Y', 'N')) ENABLE;
  ALTER TABLE "MOYEODDUGI"."NOTIFICATIONS" ADD PRIMARY KEY ("NOTI_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CHAT_MEMBERS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."CHAT_MEMBERS" ADD CONSTRAINT "FK_MEMBER_ROOM" FOREIGN KEY ("ROOM_ID")
	  REFERENCES "MOYEODDUGI"."CHAT_ROOMS" ("ROOM_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "MOYEODDUGI"."CHAT_MEMBERS" ADD CONSTRAINT "FK_MEMBER_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "MOYEODDUGI"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CHAT_MESSAGES
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."CHAT_MESSAGES" ADD CONSTRAINT "FK_MESSAGE_ROOM" FOREIGN KEY ("ROOM_ID")
	  REFERENCES "MOYEODDUGI"."CHAT_ROOMS" ("ROOM_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "MOYEODDUGI"."CHAT_MESSAGES" ADD CONSTRAINT "FK_MESSAGE_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "MOYEODDUGI"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CHAT_ROOMS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."CHAT_ROOMS" ADD CONSTRAINT "FK_ROOM_POST" FOREIGN KEY ("POST_ID")
	  REFERENCES "MOYEODDUGI"."POSTS" ("POST_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMENTS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."COMMENTS" ADD CONSTRAINT "FK_COMMENT_PARENT" FOREIGN KEY ("PARENT_ID")
	  REFERENCES "MOYEODDUGI"."COMMENTS" ("COMMENT_ID") ENABLE;
  ALTER TABLE "MOYEODDUGI"."COMMENTS" ADD CONSTRAINT "FK_COMMENTS_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "MOYEODDUGI"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "MOYEODDUGI"."COMMENTS" ADD CONSTRAINT "FK_COMMENT_REPLY_TO" FOREIGN KEY ("REPLY_TO")
	  REFERENCES "MOYEODDUGI"."COMMENTS" ("COMMENT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FOLLOWS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."FOLLOWS" ADD CONSTRAINT "FK_FOLLOWER" FOREIGN KEY ("FOLLOWER_ID")
	  REFERENCES "MOYEODDUGI"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "MOYEODDUGI"."FOLLOWS" ADD CONSTRAINT "FK_FOLLOWING" FOREIGN KEY ("FOLLOWING_ID")
	  REFERENCES "MOYEODDUGI"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LIKES
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."LIKES" ADD CONSTRAINT "FK_LIKES_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "MOYEODDUGI"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOTIFICATIONS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."NOTIFICATIONS" ADD CONSTRAINT "FK_NOTI_RECEIVER" FOREIGN KEY ("RECEIVER_ID")
	  REFERENCES "MOYEODDUGI"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "MOYEODDUGI"."NOTIFICATIONS" ADD CONSTRAINT "FK_NOTI_SENDER" FOREIGN KEY ("SENDER_ID")
	  REFERENCES "MOYEODDUGI"."USERS" ("USER_ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PATTERNS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."PATTERNS" ADD CONSTRAINT "FK_PATTERNS_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "MOYEODDUGI"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PATTERN_IMAGES
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."PATTERN_IMAGES" ADD CONSTRAINT "FK_PATTERN_IMAGES" FOREIGN KEY ("PATTERN_ID")
	  REFERENCES "MOYEODDUGI"."PATTERNS" ("PATTERN_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PATTERN_TAGS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."PATTERN_TAGS" ADD CONSTRAINT "FK_PATTERN_TAGS" FOREIGN KEY ("PATTERN_ID")
	  REFERENCES "MOYEODDUGI"."PATTERNS" ("PATTERN_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PLACES
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."PLACES" ADD CONSTRAINT "FK_PLACES_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "MOYEODDUGI"."USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PLACE_REVIEWS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."PLACE_REVIEWS" ADD CONSTRAINT "FK_REVIEWS_PLACE" FOREIGN KEY ("PLACE_ID")
	  REFERENCES "MOYEODDUGI"."PLACES" ("PLACE_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "MOYEODDUGI"."PLACE_REVIEWS" ADD CONSTRAINT "FK_REVIEWS_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "MOYEODDUGI"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POSTS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."POSTS" ADD CONSTRAINT "FK_POSTS_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "MOYEODDUGI"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POST_IMAGES
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."POST_IMAGES" ADD CONSTRAINT "FK_POST_IMAGES" FOREIGN KEY ("POST_ID")
	  REFERENCES "MOYEODDUGI"."POSTS" ("POST_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SCRAPS
--------------------------------------------------------

  ALTER TABLE "MOYEODDUGI"."SCRAPS" ADD CONSTRAINT "FK_SCRAPS_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "MOYEODDUGI"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
